// Generated by scripts/generate-contributors.mjs. CI may replace this file before build.
export const ACKNOWLEDGEMENT_CONTRIBUTORS = [
  {
    "name": "YiJie",
    "contribution": {
      "en": "Creator & maintainer",
      "zh-CN": "创建者与维护者"
    },
    "profileUrl": "https://github.com/NWYLZW",
    "avatarUrl": "https://avatars.githubusercontent.com/u/51358815?v=4"
  }
] as const
