import { COMPOSER_VISUAL_LOCALES } from './composer-visual-catalog.js'
import type {
  CordisXEffectivePointPolicy,
  CordisXExtensionPointAccessV2,
  CordisXExtensionPointAdapterSupport,
  CordisXExtensionPointAvailability,
  CordisXExtensionPointCurrentContextState,
  CordisXExtensionPointIdentity,
  CordisXExtensionPointKind,
  CordisXExtensionPointMaturity,
  CordisXExtensionPointPayloadFamily,
  CordisXExtensionPointPolicyRecordV1,
  CordisXExtensionPointRuntimeContextV1,
  CordisXExtensionPointStability,
  CordisXHostExtensionPointAnchorDescriptorV2,
  CordisXHostExtensionPointAnchorDescriptorV5,
  CordisXHostExtensionPointCatalogV1,
  CordisXHostExtensionPointCatalogV2,
  CordisXHostExtensionPointCatalogV3,
  CordisXHostExtensionPointCatalogV5,
  CordisXHostExtensionPointCatalogV6,
  CordisXHostExtensionPointCatalogV7,
  CordisXHostExtensionPointCatalogV8,
  CordisXHostExtensionPointCatalogV9,
  CordisXHostExtensionPointDescriptor,
  CordisXHostExtensionPointDescriptorV3,
  CordisXHostExtensionPointDescriptorV5,
  CordisXHostExtensionPointDescriptorV9,
  CordisXLocaleCatalog,
  CordisXLocalizedProjection,
  CordisXLocalizedText,
  CordisXPluginIdentity,
  CordisXPointPolicy,
} from '../contracts.js'
import {
  CORDISX_EXTENSION_POINT_ACCESS_SCHEMA_V2,
  CORDISX_EXTENSION_POINT_POLICY_SCHEMA_V1,
  CORDISX_EXTENSION_POINT_RUNTIME_CONTEXT_SCHEMA_V1,
  CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V1,
  CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V2,
  CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V3,
  CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V5,
  CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V6,
  CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V7,
  CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V8,
  CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V9,
} from '../contracts.js'
import type { CordisXI18nService } from './i18n.js'
import type { CommandSnapshot } from './commands.js'
import type { NavigationSnapshot, RouteSnapshot } from './navigation.js'
import type { SurfaceContributionSnapshot, SurfaceCurrentContextSnapshot } from './surfaces.js'
import { qualifyOwnedId } from './ownership.js'
import type {
  GenerationVisibilityCoordinator,
  PluginGenerationEffectIdentity,
  PluginGenerationView,
} from './generation-visibility.js'
import { assertLocalId, assertLocalizedText, ICON_TOKEN_PATTERN, immutableSnapshot } from './validation.js'

import { CATALOG_TEXT, DESCRIPTOR_NAMESPACE } from './extension-point-descriptors.js'
import { CORDISX_MANAGER_SETTINGS_NAVIGATION_GROUP_CATALOG } from './manager-settings-navigation.js'

function descriptor(
  id: string,
  kind: CordisXExtensionPointKind,
  key: string,
  fallbackTitle: string,
  fallbackDescription: string,
  icon: `host:${string}`,
  payloadFamily: CordisXExtensionPointPayloadFamily,
  maturity: CordisXExtensionPointMaturity,
  adapterSupport: CordisXExtensionPointAdapterSupport,
  options: Readonly<{
    diagnostic?: CordisXLocalizedText
    anchors?: readonly CordisXHostExtensionPointAnchorDescriptorV5[]
  }> = {},
): CordisXHostExtensionPointDescriptorV5 {
  return Object.freeze({
    id,
    kind,
    title: Object.freeze({ namespace: DESCRIPTOR_NAMESPACE, key: `${key}.title`, fallback: fallbackTitle }),
    description: Object.freeze({
      namespace: DESCRIPTOR_NAMESPACE,
      key: `${key}.description`,
      fallback: fallbackDescription,
    }),
    icon,
    payloadFamily,
    maturity,
    adapterSupport,
    ...options,
    ...(kind !== 'outlet' ? {} : {
      pageChrome: Object.freeze(['standard'] as const),
      presentationGroup: id,
      routePathFamily: id === 'app'
        ? 'app' as const
        : id === 'main'
        ? 'main' as const
        : id === 'session.content'
        ? 'session' as const
        : 'host-defined' as const,
    }),
  })
}

function diagnostic(key: string, fallback: string): CordisXLocalizedText {
  return Object.freeze({ namespace: DESCRIPTOR_NAMESPACE, key: `diagnostic.${key}`, fallback })
}

const RESERVED = Object.freeze({
  diagnostic: diagnostic('reserved', 'Reserved by the protocol; this host does not support this seat.'),
})
const UNVERIFIED_ADAPTER = Object.freeze({
  diagnostic: diagnostic('adapter-unverified', 'This adapter seat is not release-verified.'),
})

export const CORDISX_BUILTIN_EXTENSION_POINT_CATALOG = Object.freeze({
  $schema: CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V8,
  schemaVersion: 8,
  points: Object.freeze([
    descriptor(
      'sidebar.footer.before-control',
      'surface',
      'sidebar.footer.before-control',
      'Sidebar footer before control',
      'Adds a compact action before the designated sidebar footer control.',
      'host:open',
      'action',
      'stable',
      'supported',
    ),
    descriptor(
      'sidebar.footer.after-control',
      'surface',
      'sidebar.footer.after-control',
      'Sidebar footer after control',
      'Adds a compact action after the designated sidebar footer control.',
      'host:open',
      'action',
      'stable',
      'supported',
    ),
    descriptor(
      'sidebar.footer.menu',
      'surface',
      'sidebar.footer.menu',
      'Sidebar footer menu',
      'Adds a host-rendered command to the designated footer control menu.',
      'host:more',
      'menu-item',
      'stable',
      'supported',
    ),
    descriptor(
      'sidebar.account.menu',
      'surface',
      'sidebar.account.menu',
      'Sidebar account menu',
      'Adds a host-rendered command to the native account/profile menu.',
      'host:more',
      'menu-item',
      'stable',
      'supported',
    ),
    descriptor(
      'sidebar.navigation.items',
      'surface',
      'sidebar.navigation.items',
      'Sidebar navigation',
      'Adds a navigation row with a primary action and optional independent shortcuts.',
      'host:layers',
      'navigation-item',
      'stable',
      'supported',
    ),
    descriptor(
      'sidebar.workspace.menu',
      'surface',
      'sidebar.workspace.menu',
      'Workspace menu',
      'Adds host-rendered items to the native workspace menu when its seat is resolved.',
      'host:more',
      'menu-item',
      'experimental',
      'unverified',
      UNVERIFIED_ADAPTER,
    ),
    descriptor(
      'sidebar.session.actions',
      'surface',
      'sidebar.session.actions',
      'Session row actions',
      'Adds contextual actions to an identified native session row.',
      'host:more',
      'contextual-action',
      'reserved',
      'unsupported',
      RESERVED,
    ),
    descriptor(
      'sidebar.session.menu',
      'surface',
      'sidebar.session.menu',
      'Session row menu',
      'Adds contextual items to an identified native session menu.',
      'host:more',
      'contextual-action',
      'reserved',
      'unsupported',
      RESERVED,
    ),
    descriptor(
      'workspace.toolbar.items',
      'surface',
      'workspace.toolbar.items',
      'Workspace toolbar',
      'Adds an action before, after, or inside the menu of a semantic workspace toolbar anchor.',
      'host:more',
      'action',
      'stable',
      'supported',
      {
        anchors: Object.freeze([{
          id: 'workspace.primary',
          placements: Object.freeze(['before', 'after', 'menu'] as const),
          adapterSupport: 'supported',
        }]),
      },
    ),
    descriptor(
      'session.header.actions',
      'surface',
      'session.header.actions',
      'Session header actions',
      'Adds host-rendered action and utility groups to the active native session header.',
      'host:more',
      'contextual-action',
      'stable',
      'supported',
    ),
    descriptor(
      'session.tabs',
      'surface',
      'session.tabs',
      'Session tabs',
      'Adds controlled view entries navigated and rendered by the host.',
      'host:layers',
      'tab',
      'reserved',
      'unsupported',
      RESERVED,
    ),
    descriptor(
      'session.banner.items',
      'surface',
      'session.banner.items',
      'Session banners',
      'Adds limited structured banners to the active session.',
      'host:info',
      'presenter',
      'reserved',
      'unsupported',
      RESERVED,
    ),
    descriptor(
      'session.message.actions',
      'surface',
      'session.message.actions',
      'Message actions',
      'Adds contextual actions to a canonically identified message.',
      'host:more',
      'contextual-action',
      'reserved',
      'unsupported',
      { diagnostic: diagnostic('message-identity', 'Canonical message identity is unavailable.') },
    ),
    descriptor(
      'session.turn.footer',
      'surface',
      'session.turn.footer',
      'Turn footer',
      'Adds a structured presenter after a canonically identified turn.',
      'host:info',
      'presenter',
      'reserved',
      'unsupported',
      RESERVED,
    ),
    descriptor(
      'session.tool.actions',
      'surface',
      'session.tool.actions',
      'Tool actions',
      'Adds contextual actions to a canonically identified tool item.',
      'host:more',
      'contextual-action',
      'reserved',
      'unsupported',
      { diagnostic: diagnostic('tool-identity', 'Canonical tool identity is unavailable.') },
    ),
    descriptor(
      'session.backdrop',
      'surface',
      'session.backdrop',
      'Session backdrop',
      'Projects a structured, pointer-inert ambience and portrait behind the active session.',
      'host:layers',
      'session-backdrop-presentation',
      'stable',
      'supported',
    ),
    descriptor(
      'composer.toolbar.items',
      'surface',
      'composer.toolbar.items',
      'Composer toolbar',
      'Adds a host-rendered action at a verified semantic composer anchor.',
      'host:more',
      'contextual-action',
      'stable',
      'supported',
      {
        anchors: Object.freeze([
          { id: 'submit', placements: Object.freeze(['before'] as const), adapterSupport: 'supported' },
          {
            id: 'leading',
            placements: Object.freeze(['before', 'after'] as const),
            adapterSupport: 'unverified',
            diagnostic: diagnostic('anchor-unverified', 'This anchor is not release-verified.'),
          },
          {
            id: 'model',
            placements: Object.freeze(['before', 'after', 'menu'] as const),
            adapterSupport: 'unverified',
            diagnostic: diagnostic('anchor-unverified', 'This anchor is not release-verified.'),
          },
        ]),
      },
    ),
    descriptor(
      'composer.reasoning-intensity',
      'surface',
      'composer.reasoning-intensity',
      'Reasoning intensity',
      'Projects a structured visual theme over the uniquely resolved native reasoning-intensity range.',
      'host:layers',
      'reasoning-intensity-presentation',
      'stable',
      'supported',
    ),
    descriptor(
      'composer.submit.effects',
      'surface',
      'composer.submit.effects',
      'Composer submit effects',
      'Provides a Host-owned transparent canvas to one isolated worker after a semantic composer submit.',
      'host:layers',
      'transient-canvas-presentation',
      'experimental',
      'supported',
    ),
    descriptor(
      'composer.command-menu.items',
      'surface',
      'composer.command-menu.items',
      'Composer command menu',
      'Adds host-rendered items to the existing native composer command menu.',
      'host:more',
      'contextual-action',
      'experimental',
      'unverified',
      UNVERIFIED_ADAPTER,
    ),
    descriptor(
      'composer.dock.above',
      'surface',
      'composer.dock.above',
      'Composer dock above',
      'Adds a limited structured presenter above the composer.',
      'host:info',
      'presenter',
      'experimental',
      'unverified',
      UNVERIFIED_ADAPTER,
    ),
    descriptor(
      'composer.dock.below',
      'surface',
      'composer.dock.below',
      'Composer dock below',
      'Adds a limited structured presenter below the composer.',
      'host:info',
      'presenter',
      'experimental',
      'unverified',
      UNVERIFIED_ADAPTER,
    ),
    descriptor(
      'panel.right.header-actions',
      'surface',
      'panel.right.header-actions',
      'Right panel actions',
      'Adds contextual actions to a verified visible right panel header.',
      'host:more',
      'contextual-action',
      'experimental',
      'unverified',
      UNVERIFIED_ADAPTER,
    ),
    descriptor(
      'panel.right.tabs',
      'surface',
      'panel.right.tabs',
      'Right panel tabs',
      'Adds host-controlled tabs to the right panel.',
      'host:layers',
      'tab',
      'reserved',
      'unsupported',
      RESERVED,
    ),
    descriptor(
      'panel.bottom.header-actions',
      'surface',
      'panel.bottom.header-actions',
      'Bottom panel actions',
      'Adds contextual actions to a verified visible bottom panel header.',
      'host:more',
      'contextual-action',
      'experimental',
      'unverified',
      UNVERIFIED_ADAPTER,
    ),
    descriptor(
      'panel.bottom.tabs',
      'surface',
      'panel.bottom.tabs',
      'Bottom panel tabs',
      'Adds host-controlled tabs to the bottom panel.',
      'host:layers',
      'tab',
      'reserved',
      'unsupported',
      RESERVED,
    ),
    descriptor(
      'environment.panel.header-actions',
      'surface',
      'environment.panel.header-actions',
      'Environment panel header',
      'Adds a command action to the environment panel header.',
      'host:settings',
      'action',
      'stable',
      'supported',
    ),
    descriptor(
      'environment.panel.sections',
      'surface',
      'environment.panel.sections',
      'Environment panel sections',
      'Adds a host-rendered section to the environment panel.',
      'host:layers',
      'environment-section',
      'stable',
      'supported',
    ),
    descriptor(
      'environment.section.actions',
      'surface',
      'environment.section.actions',
      'Environment section actions',
      'Adds a command action to a declared environment section.',
      'host:settings',
      'action',
      'stable',
      'supported',
    ),
    descriptor(
      'environment.section.rows',
      'surface',
      'environment.section.rows',
      'Environment section rows',
      'Adds a structured label, value, description, and status row to a declared section.',
      'host:info',
      'environment-row',
      'stable',
      'supported',
    ),
    descriptor(
      'environment.row.trailing-actions',
      'surface',
      'environment.row.trailing-actions',
      'Environment row actions',
      'Adds an independent command action to the end of a declared environment row.',
      'host:more',
      'action',
      'stable',
      'supported',
    ),
    descriptor(
      'app',
      'outlet',
      'outlet.app',
      'Application page',
      'Opens a CordisX page over the renderer application region without replacing native content.',
      'host:open',
      'outlet',
      'stable',
      'supported',
    ),
    descriptor(
      'main',
      'outlet',
      'outlet.main',
      'Main workspace page',
      'Opens a CordisX page over the region to the right of the sidebar and follows the current main context.',
      'host:layers',
      'outlet',
      'stable',
      'supported',
    ),
    descriptor(
      'session.content',
      'outlet',
      'outlet.session.content',
      'Session content page',
      'Opens a CordisX page below the active session header while preserving side and bottom panels.',
      'host:history',
      'outlet',
      'stable',
      'supported',
    ),
    descriptor(
      'panel.right.content',
      'outlet',
      'outlet.panel.right.content',
      'Right panel content',
      'Hosts controlled trusted-local page content in the right panel.',
      'host:layers',
      'outlet',
      'reserved',
      'unsupported',
      RESERVED,
    ),
    descriptor(
      'panel.bottom.content',
      'outlet',
      'outlet.panel.bottom.content',
      'Bottom panel content',
      'Hosts controlled trusted-local page content in the bottom panel.',
      'host:layers',
      'outlet',
      'reserved',
      'unsupported',
      RESERVED,
    ),
  ]),
}) satisfies CordisXHostExtensionPointCatalogV8

export const CORDISX_MANAGER_EXTENSION_POINT_CATALOG = Object.freeze({
  $schema: CORDISX_HOST_EXTENSION_POINT_CATALOG_SCHEMA_V9,
  schemaVersion: 9,
  points: Object.freeze([
    Object.freeze({
      id: 'manager.settings.tabs',
      kind: 'surface',
      title: Object.freeze({
        namespace: DESCRIPTOR_NAMESPACE,
        key: 'manager.settings.tabs.title',
        fallback: 'Manager settings content tabs',
      }),
      description: Object.freeze({
        namespace: DESCRIPTOR_NAMESPACE,
        key: 'manager.settings.tabs.description',
        fallback:
          'Compatibility surface for Hosts that expose Settings; it is not mounted in the current Manager layout.',
      }),
      icon: 'host:settings',
      payloadFamily: 'manager-settings-content-tab',
      maturity: 'stable',
      adapterSupport: 'supported',
    }),
    Object.freeze({
      id: 'manager.settings.content',
      kind: 'outlet',
      title: Object.freeze({
        namespace: DESCRIPTOR_NAMESPACE,
        key: 'manager.settings.content.title',
        fallback: 'Manager settings content',
      }),
      description: Object.freeze({
        namespace: DESCRIPTOR_NAMESPACE,
        key: 'manager.settings.content.description',
        fallback:
          'Compatibility body outlet for a mounted Settings content tab; it is not mounted in the current Manager layout.',
      }),
      icon: 'host:settings',
      payloadFamily: 'outlet',
      maturity: 'stable',
      adapterSupport: 'supported',
      pageChrome: Object.freeze(['body-only'] as const),
      presentationGroup: 'manager.settings',
      routePathFamily: 'manager-settings',
    }),
    Object.freeze({
      id: 'manager.settings.navigation-items',
      kind: 'surface',
      title: Object.freeze({
        namespace: DESCRIPTOR_NAMESPACE,
        key: 'manager.settings.navigation-items.title',
        fallback: 'Manager settings navigation items',
      }),
      description: Object.freeze({
        namespace: DESCRIPTOR_NAMESPACE,
        key: 'manager.settings.navigation-items.description',
        fallback: 'Adds an independent Host-rendered plugin destination across the Manager settings extension seam.',
      }),
      icon: 'host:layers',
      payloadFamily: 'manager-settings-navigation-item-v2',
      maturity: 'stable',
      adapterSupport: 'supported',
      navigationGroups: CORDISX_MANAGER_SETTINGS_NAVIGATION_GROUP_CATALOG,
    }),
    Object.freeze({
      id: 'manager.content',
      kind: 'outlet',
      title: Object.freeze({
        namespace: DESCRIPTOR_NAMESPACE,
        key: 'manager.content.title',
        fallback: 'Manager content',
      }),
      description: Object.freeze({
        namespace: DESCRIPTOR_NAMESPACE,
        key: 'manager.content.description',
        fallback: 'Mounts a trusted-local plugin body beneath a standard Host-owned Manager page header.',
      }),
      icon: 'host:layers',
      payloadFamily: 'outlet',
      maturity: 'stable',
      adapterSupport: 'supported',
      pageChrome: Object.freeze(['standard'] as const),
      presentationGroup: 'manager',
      routePathFamily: 'manager',
    }),
  ]),
}) satisfies CordisXHostExtensionPointCatalogV9

const ALL_EXTENSION_POINT_DESCRIPTORS: readonly CordisXHostExtensionPointDescriptorV9[] = [
  ...CORDISX_BUILTIN_EXTENSION_POINT_CATALOG.points,
  ...CORDISX_MANAGER_EXTENSION_POINT_CATALOG.points,
] as const

const EN_MESSAGES = Object.fromEntries([
  ...ALL_EXTENSION_POINT_DESCRIPTORS.flatMap(point => [
    [point.title.key, point.title.fallback!],
    [point.description.key, point.description.fallback!],
    ...(point.diagnostic === undefined ? [] : [[point.diagnostic.key, point.diagnostic.fallback!]]),
    ...(point.anchors ?? []).flatMap(anchor =>
      anchor.diagnostic === undefined ? [] : [[anchor.diagnostic.key, anchor.diagnostic.fallback!]]
    ),
    ...('navigationGroups' in point
      ? point.navigationGroups.groups.map(group => [group.label.key, group.label.fallback] as const)
      : []),
  ]),
  ...Object.values(CATALOG_TEXT).map(message => [message.key, message.fallback!]),
])

const ZH_MESSAGES: Readonly<Record<string, string>> = {
  'sidebar.footer.before-control.title': '侧边栏底部前置操作',
  'sidebar.footer.before-control.description': '在侧边栏底部指定控件左侧添加紧凑操作。',
  'sidebar.footer.after-control.title': '侧边栏底部后置操作',
  'sidebar.footer.after-control.description': '在侧边栏底部指定控件右侧添加紧凑操作。',
  'sidebar.footer.menu.title': '侧边栏底部菜单',
  'sidebar.footer.menu.description': '向侧边栏底部指定控件的菜单添加宿主渲染命令。',
  'sidebar.account.menu.title': '侧边栏账户菜单',
  'sidebar.account.menu.description': '向原生账户或个人资料菜单添加宿主渲染命令。',
  'sidebar.navigation.items.title': '侧边栏导航',
  'sidebar.navigation.items.description': '添加带主操作和独立快捷操作的导航条目。',
  'sidebar.workspace.menu.title': '工作区菜单',
  'sidebar.workspace.menu.description': '当原生位置已定位时，向工作区菜单添加由宿主渲染的条目。',
  'sidebar.session.actions.title': '会话条目操作',
  'sidebar.session.actions.description': '向已识别的原生会话条目添加上下文操作。',
  'sidebar.session.menu.title': '会话条目菜单',
  'sidebar.session.menu.description': '向已识别的原生会话菜单添加上下文条目。',
  'workspace.toolbar.items.title': '工作区工具栏',
  'workspace.toolbar.items.description': '在语义工具栏锚点前后或菜单中添加操作。',
  'session.header.actions.title': '会话标题操作',
  'session.header.actions.description': '向当前原生会话标题添加由宿主渲染的操作和工具分组。',
  'session.tabs.title': '会话标签页',
  'session.tabs.description': '添加由宿主导航和渲染的受控视图入口。',
  'session.banner.items.title': '会话横幅',
  'session.banner.items.description': '向当前会话添加有限的结构化横幅。',
  'session.message.actions.title': '消息操作',
  'session.message.actions.description': '向具有规范标识的消息添加上下文操作。',
  'session.turn.footer.title': '轮次尾部',
  'session.turn.footer.description': '在具有规范标识的轮次之后添加结构化展示项。',
  'session.tool.actions.title': '工具项操作',
  'session.tool.actions.description': '向具有规范标识的工具项添加上下文操作。',
  'session.backdrop.title': '会话背景',
  'session.backdrop.description': '在当前会话后方投射结构化且不接收指针事件的氛围和人像。',
  'composer.toolbar.items.title': '输入区工具栏',
  'composer.toolbar.items.description': '在已验证的语义输入区锚点添加由宿主渲染的操作。',
  'composer.reasoning-intensity.title': '思考强度',
  'composer.reasoning-intensity.description': '在唯一识别的原生思考强度滑块上投射结构化视觉主题。',
  'composer.submit.effects.title': '发送特效',
  'composer.submit.effects.description': '在语义化发送后向一个隔离 Worker 提供由 Host 管理的透明画布。',
  'composer.command-menu.items.title': '输入区命令菜单',
  'composer.command-menu.items.description': '向现有原生输入区命令菜单添加由宿主渲染的条目。',
  'composer.dock.above.title': '输入区上方停靠区',
  'composer.dock.above.description': '在输入区上方添加有限的结构化展示项。',
  'composer.dock.below.title': '输入区下方停靠区',
  'composer.dock.below.description': '在输入区下方添加有限的结构化展示项。',
  'panel.right.header-actions.title': '右侧面板操作',
  'panel.right.header-actions.description': '向已验证且可见的右侧面板标题区添加上下文操作。',
  'panel.right.tabs.title': '右侧面板标签页',
  'panel.right.tabs.description': '向右侧面板添加由宿主控制的标签页。',
  'panel.bottom.header-actions.title': '底部面板操作',
  'panel.bottom.header-actions.description': '向已验证且可见的底部面板标题区添加上下文操作。',
  'panel.bottom.tabs.title': '底部面板标签页',
  'panel.bottom.tabs.description': '向底部面板添加由宿主控制的标签页。',
  'environment.panel.header-actions.title': '环境面板标题操作',
  'environment.panel.header-actions.description': '向环境面板标题区添加命令操作。',
  'environment.panel.sections.title': '环境面板分区',
  'environment.panel.sections.description': '向环境面板添加由宿主渲染的分区。',
  'environment.section.actions.title': '环境分区操作',
  'environment.section.actions.description': '向已声明的环境分区添加命令操作。',
  'environment.section.rows.title': '环境分区条目',
  'environment.section.rows.description': '向已声明的分区添加结构化标签、值、说明和状态。',
  'environment.row.trailing-actions.title': '环境条目尾部操作',
  'environment.row.trailing-actions.description': '向环境条目末尾添加独立命令操作。',
  'outlet.app.title': '应用页面',
  'outlet.app.description': '在整个 renderer 应用区域上覆盖 CordisX 页面，不替换原生内容。',
  'outlet.main.title': '主工作区页面',
  'outlet.main.description': '在侧边栏右侧区域覆盖 CordisX 页面，并跟随当前主上下文。',
  'outlet.session.content.title': '会话内容页面',
  'outlet.session.content.description': '在当前会话标题下方覆盖 CordisX 页面，同时保留侧边和底部面板。',
  'outlet.panel.right.content.title': '右侧面板内容',
  'outlet.panel.right.content.description': '在右侧面板承载受控的可信本地页面内容。',
  'outlet.panel.bottom.content.title': '底部面板内容',
  'outlet.panel.bottom.content.description': '在底部面板承载受控的可信本地页面内容。',
  'manager.settings.tabs.title': '管理器配置内容标签页',
  'manager.settings.tabs.description': '兼容仍提供配置页的宿主；当前管理器布局未挂载此点位。',
  'manager.settings.content.title': '管理器配置内容',
  'manager.settings.content.description': '兼容已挂载的配置内容标签页；当前管理器布局未挂载此出口。',
  'manager.settings.navigation-items.title': '管理器配置导航条目',
  'manager.settings.navigation-items.description': '跨越管理器配置扩展缝隙添加由宿主渲染的独立插件页面入口。',
  'manager.settings.navigation-group.resources': '资源',
  'manager.settings.navigation-group.development': '开发',
  'manager.settings.navigation-group.collaboration': '协作',
  'manager.settings.navigation-group.other': '其他',
  'manager.content.title': '管理器内容',
  'manager.content.description': '在宿主拥有的标准管理器页面标题下挂载受控的可信本地插件正文。',
  'diagnostic.anchor': '当前未定位到原生宿主点位。',
  'diagnostic.adapter-unverified': '该适配器点位尚未通过发布验证。',
  'diagnostic.anchor-unverified': '该锚点尚未通过发布验证。',
  'diagnostic.message-identity': '当前无法取得规范消息标识。',
  'diagnostic.reserved': '协议已保留该点位；当前宿主未开放安全位置。',
  'diagnostic.tool-identity': '当前无法取得规范工具标识。',
  'catalog.category.surface': '界面点位',
  'catalog.category.outlet': '页面出口',
  'catalog.owner.host': 'CordisX 宿主',
  'catalog.status.pending': '待定位',
  'catalog.status.unavailable': '不可用',
  'catalog.status.error': '需要处理',
  'catalog.status.denied': '访问已拒绝',
}

export const CORDISX_EXTENSION_POINT_LOCALE_CATALOGS: readonly CordisXLocaleCatalog[] = Object.freeze([
  Object.freeze({ namespace: DESCRIPTOR_NAMESPACE, locale: 'en', default: true, messages: Object.freeze(EN_MESSAGES) }),
  Object.freeze({ namespace: DESCRIPTOR_NAMESPACE, locale: 'zh-CN', messages: Object.freeze(ZH_MESSAGES) }),
  ...COMPOSER_VISUAL_LOCALES,
])
