export function modelProviderCopy(locale: string) {
  return locale.startsWith('zh')
    ? {
      providers: '模型服务',
      official: 'Codex 官方',
      models: '模型',
      reasoningEffort: '思考强度',
      enableFastMode: '开启 Fast 模式',
      disableFastMode: '关闭 Fast 模式',
      reasoningEffortLabel: (effort?: string) =>
        ({
          none: '无',
          minimal: '最低',
          low: '轻度',
          medium: '中等',
          high: '高',
          xhigh: '超高',
          max: '最高',
          ultra: '极高',
        })[effort ?? ''] ?? effort ?? '选择强度',
      search: '搜索服务或模型',
      searchProviders: '搜索模型服务',
      searchModels: '搜索模型',
      clearSearch: '清空搜索',
      noProviderMatches: '没有匹配的模型服务',
      noMatches: '没有匹配的模型',
      refresh: '刷新',
      empty: '暂无可用的模型服务',
      emptyModels: '暂无可用模型',
      loading: '正在加载…',
      loadFailed: '加载失败，请重试',
      unavailable: '模型服务暂不可用',
      choose: '选择模型',
      back: '返回服务列表',
      actions: '服务操作',
      unsupportedIntent: '当前操作暂不支持切换模型服务。请使用普通发送，或选回当前服务。',
      submitRejected: '此次发送未执行，模型服务状态已变化，请重试。',
      switching: '正在切换模型服务…',
      accepted: '正在同步模型服务…',
      switched: '模型服务已切换',
      updated: '思考强度已更新',
      busy: '当前回复结束后才能切换',
      failed: '切换未完成，请检查服务状态后重试',
      actionFailed: '操作未完成，请重试',
      active: '当前',
      unknown: '选择服务',
    }
    : {
      providers: 'Model services',
      official: 'Codex',
      models: 'Models',
      reasoningEffort: 'Reasoning effort',
      enableFastMode: 'Enable Fast mode',
      disableFastMode: 'Disable Fast mode',
      reasoningEffortLabel: (effort?: string) =>
        ({
          none: 'None',
          minimal: 'Minimal',
          low: 'Light',
          medium: 'Medium',
          high: 'High',
          xhigh: 'Extra High',
          max: 'Max',
          ultra: 'Ultra',
        })[effort ?? ''] ?? effort ?? 'Choose effort',
      search: 'Search services or models',
      searchProviders: 'Search model services',
      searchModels: 'Search models',
      clearSearch: 'Clear search',
      noProviderMatches: 'No matching model services',
      noMatches: 'No matching models',
      refresh: 'Refresh',
      empty: 'No model services available',
      emptyModels: 'No models available',
      loading: 'Loading…',
      loadFailed: 'Could not load. Try again.',
      unavailable: 'Model services unavailable',
      choose: 'Choose model',
      back: 'Back to providers',
      actions: 'Service actions',
      unsupportedIntent:
        'This action does not support switching model services yet. Use Send or select the current service.',
      submitRejected: 'Send was not run because the model service state changed. Try again.',
      switching: 'Switching model service…',
      accepted: 'Synchronizing model service…',
      switched: 'Model service switched',
      updated: 'Reasoning effort updated',
      busy: 'Wait for the current response before switching',
      failed: 'Switch incomplete. Check the service and retry.',
      actionFailed: 'Action failed. Please retry.',
      active: 'Current',
      unknown: 'Choose provider',
    }
}
