export const AGENT_CONVERSATION_STYLES = `
.cxa-root{--cxa-content-max:780px;--cxa-layout-space:var(--cx-space-6,24px);position:relative;display:grid;min-width:0;min-height:0;height:100%;grid-template-rows:auto minmax(0,1fr);overflow:hidden;background:var(--cx-surface);color:var(--cx-text);font:14px/1.5 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.cxa-root,.cxa-root *,.cxa-root *::before,.cxa-root *::after{box-sizing:border-box}
.cxa-chrome{position:relative;z-index:2;display:flex;min-width:0;min-height:58px;align-items:center;padding:9px var(--cxa-layout-space);border-bottom:1px solid var(--cx-border);background:var(--cx-surface)}.cxa-chrome-inner{display:flex;width:min(100%,var(--cxa-content-max));min-width:0;align-items:center;justify-content:space-between;gap:16px;margin-inline:auto}
.cxa-title-block{display:grid;min-width:0;gap:1px}.cxa-title{min-width:0;overflow:hidden;margin:0;color:var(--cx-text);font:inherit;font-size:14px;font-weight:650;line-height:20px;text-overflow:ellipsis;white-space:nowrap}.cxa-participants{min-width:0;overflow:hidden;color:var(--cx-muted);font-size:10px;line-height:15px;text-overflow:ellipsis;white-space:nowrap}
.cxa-header-actions,.cxa-message-actions{display:flex;min-width:0;align-items:center;gap:5px}.cxa-action,.cxa-send{appearance:none;display:inline-flex;min-height:30px;align-items:center;justify-content:center;gap:6px;border:0;border-radius:8px;padding:5px 9px;background:transparent;color:var(--cx-muted);font:inherit;font-size:12px;font-weight:600;line-height:18px;cursor:pointer}.cxa-action:hover:not(:disabled){background:var(--cx-hover);color:var(--cx-text)}.cxa-action:active:not(:disabled){background:var(--cx-pressed)}.cxa-action:focus-visible,.cxa-send:focus-visible,.cxa-draft:focus-visible,.cxa-timeline:focus-visible{outline:2px solid var(--cx-focus);outline-offset:-2px}.cxa-action:disabled,.cxa-send:disabled{cursor:not-allowed;opacity:var(--cx-disabled)}.cxa-action .cordisx-host-icon{display:inline-flex;width:16px;height:16px;align-items:center;justify-content:center;color:currentColor}.cxa-action .cordisx-host-icon>svg{width:1em;height:1em;fill:currentColor;stroke:currentColor}
.cxa-body{display:grid;min-width:0;min-height:0;grid-template-rows:minmax(0,1fr) auto;overflow:hidden}.cxa-timeline{min-width:0;min-height:0;overflow-x:hidden;overflow-y:auto;overscroll-behavior:contain;padding:var(--cxa-layout-space);scrollbar-gutter:stable}.cxa-timeline-list{display:flex;width:min(100%,var(--cxa-content-max));min-width:0;min-height:0;flex:none;flex-direction:column;align-items:stretch;justify-content:flex-start;gap:var(--cxa-layout-space);margin:0 auto;padding:0}.cxa-entry{min-width:0;margin:0}.cxa-message{display:flex;width:100%;min-width:0;align-items:flex-start;gap:10px;color:var(--cx-text)}.cxa-message[data-role="human"]{justify-content:flex-end}.cxa-message[data-group-start="false"] .cxa-avatar{visibility:hidden}.cxa-avatar{display:inline-grid;width:27px;height:27px;flex:none;place-items:center;border:1px solid color-mix(in srgb,var(--cx-primary) 30%,var(--cx-border));border-radius:8px;background:color-mix(in srgb,var(--cx-primary) 10%,var(--cx-surface));color:var(--cx-text);font:700 9px/1 inherit;letter-spacing:.02em}.cxa-message-content{display:grid;min-width:0;max-width:min(88%,720px);gap:7px}.cxa-message[data-role="human"] .cxa-message-content{max-width:min(78%,600px);padding:10px 13px;border-radius:15px 15px 4px 15px;background:var(--cx-hover)}.cxa-message-meta{display:flex;min-width:0;align-items:center;gap:7px;color:var(--cx-muted);font-size:10px;line-height:14px}.cxa-message[data-role="human"] .cxa-message-meta{justify-content:flex-end}.cxa-author{overflow:hidden;color:var(--cx-text);font-weight:650;text-overflow:ellipsis;white-space:nowrap}.cxa-message-body{display:grid;gap:8px;overflow-wrap:anywhere}.cxa-message-body p{margin:0;white-space:pre-wrap}.cxa-message-state{display:inline-flex;align-items:center;gap:4px}.cxa-message[data-run-state="running"] .cxa-message-state,.cxa-status[data-state="working"]{color:var(--cx-primary)}.cxa-message[data-run-state="failed"] .cxa-message-state,.cxa-message[data-delivery-state="failed"] .cxa-message-state,.cxa-status[data-state="error"]{color:var(--cx-danger)}.cxa-message[data-run-state="stopped"] .cxa-message-state,.cxa-status[data-state="warning"]{color:var(--cx-muted)}.cxa-message-actions{margin-top:1px}.cxa-message-actions .cxa-action{min-height:27px;padding:3px 7px;font-size:11px}
.cxa-message-reactions{display:flex;flex-wrap:wrap;gap:5px}.cxa-message-reaction{display:inline-flex;align-items:center;gap:4px;padding:2px 7px 2px 3px;border:1px solid var(--cx-border);border-radius:999px;background:var(--cx-surface-raised,var(--cx-surface));color:var(--cx-muted);font-size:11px;line-height:16px}.cxa-message-reaction-avatar{display:inline-grid;width:16px;height:16px;flex:none;place-items:center}.cxa-message-reaction-avatar>.cxa-avatar{width:16px;height:16px;border-radius:5px;font-size:6px}.cxa-message-reaction-actor{color:var(--cx-text);font-weight:600}.cxa-message-reaction[data-reaction-state="pending"]{opacity:.72}.cxa-message-reaction[data-reaction-state="failed"]{border-color:color-mix(in srgb,var(--cx-danger) 55%,var(--cx-border));color:var(--cx-danger)}
.cxa-avatar{overflow:hidden;pointer-events:none}.cxa-avatar-initials{display:inline-grid;width:100%;height:100%;place-items:center}.cxa-avatar-renderer{width:100%;height:100%}.cxa-avatar .oneworks-avatar svg,.cxa-avatar .oneworks-avatar canvas{display:block;width:100%;height:100%}
.cx-agent-identity-avatar-button{appearance:none;display:inline-grid;width:27px;height:27px;flex:none;align-self:flex-start;margin:0;padding:0;border:0;border-radius:8px;outline:0;background:transparent;box-shadow:none;color:inherit;font:inherit;line-height:0;cursor:pointer}.cx-agent-identity-avatar-button:hover{filter:brightness(1.04)}.cx-agent-identity-avatar-button:focus:not(:focus-visible){outline:0;box-shadow:none}.cx-agent-identity-avatar-button:focus-visible{outline:2px solid var(--cx-focus,var(--cx-primary));outline-offset:2px;box-shadow:none}
.cxa-status{display:flex;max-width:100%;align-items:center;align-self:center;gap:8px;padding:7px 10px;border:1px solid var(--cx-border);border-radius:9px;background:color-mix(in srgb,var(--cx-surface-raised) 82%,transparent);color:var(--cx-muted);font-size:11px}.cxa-status-dot{width:7px;height:7px;flex:none;border-radius:50%;background:currentColor}.cxa-status[data-state="working"] .cxa-status-dot{animation:cxa-pulse 1.2s ease-in-out infinite}
.cxa-runtime-status{display:grid;min-height:100%;place-items:center;padding:32px;color:var(--cx-muted);font-size:12px;text-align:center}.cxa-runtime-status p{margin:0}
.cxa-composer-region{position:relative;z-index:2;width:100%;margin:0;padding:0 var(--cxa-layout-space) var(--cxa-layout-space)}.cxa-composer{display:grid;width:min(100%,var(--cxa-content-max));gap:7px;margin-inline:auto;padding:10px 10px 9px;border:1px solid var(--cx-border);border-radius:16px;background:var(--cx-surface-raised);box-shadow:0 6px 20px color-mix(in srgb,var(--cx-shadow) 20%,transparent)}.cxa-draft{display:block;width:100%;min-height:46px;max-height:180px;resize:vertical;border:0;border-radius:8px;padding:3px 4px;outline:0;background:transparent;color:var(--cx-text);font:inherit}.cxa-draft::placeholder{color:var(--cx-muted)}.cxa-composer-footer{display:flex;min-width:0;align-items:center;justify-content:flex-end;gap:8px}.cxa-composer-notice{min-width:0;flex:1;margin:0;color:var(--cx-muted);font-size:10px;overflow-wrap:anywhere}.cxa-composer-notice[data-error="true"]{color:var(--cx-danger)}.cxa-send{width:30px;height:30px;min-height:30px;flex:none;border-radius:50%;padding:0;background:var(--cx-primary);color:var(--cx-primary-text);font-size:17px}.cxa-live-region{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);clip-path:inset(50%);white-space:nowrap}
@keyframes cxa-pulse{0%,100%{opacity:.4}50%{opacity:1}}
@media (max-width:620px){.cxa-root{--cxa-layout-space:var(--cx-space-4,16px)}.cxa-chrome{min-height:54px}.cxa-title{font-size:13px}.cxa-action-copy{display:none}.cxa-action{width:30px;padding-inline:0}.cxa-message-content{max-width:calc(100% - 37px)}.cxa-message[data-role="human"] .cxa-message-content{max-width:88%}.cxa-composer{border-radius:14px}.cxa-status{max-width:100%}}
@media (prefers-reduced-motion:reduce){.cxa-status[data-state="working"] .cxa-status-dot,.cxa-avatar *{animation:none!important;transition:none!important}}
`
