import { readFile } from 'node:fs/promises'
import { expect } from 'vitest'
import { settle } from './bundle.fixtures.js'
import type { verifyRoutes } from './bundle.routes.js'

export async function verifyManagerShell(context: Awaited<ReturnType<typeof verifyRoutes>>) {
  const { config, plugin, bundle, dom, native, nativeParent, runtime, snapshot, sessionId, help } = context
  const managerTrigger = dom.window.document.querySelector<HTMLButtonElement>('[data-cordisx-manager-trigger]')
  expect(managerTrigger?.getAttribute('aria-label')).toBe('管理 CordisX 插件')
  expect(managerTrigger?.classList.contains('cordisx-icon-only-control')).toBe(false)
  expect(dom.window.getComputedStyle(managerTrigger!).display).toBe('inline-flex')
  expect(dom.window.getComputedStyle(managerTrigger!).alignItems).toBe('center')
  expect(dom.window.getComputedStyle(managerTrigger!).justifyContent).toBe('center')
  expect(managerTrigger?.querySelector('svg')).toBeNull()
  const triggerMark = managerTrigger?.querySelector<HTMLElement>('.cxr-trigger-mark')
  const triggerDark = triggerMark?.querySelector<HTMLImageElement>('.cxr-brand-mark-dark')
  const triggerLight = triggerMark?.querySelector<HTMLImageElement>('.cxr-brand-mark-light')
  expect(dom.window.getComputedStyle(triggerMark!).width).toBe('20px')
  expect(dom.window.getComputedStyle(triggerMark!).height).toBe('20px')
  expect(decodeURIComponent(triggerDark?.src ?? '')).toContain('for dark backgrounds')
  expect(decodeURIComponent(triggerDark?.src ?? '')).toContain('stroke="#fcfcfc"')
  expect(dom.window.document.getElementById('cordisx-react-manager-style')?.textContent).not.toContain('mask-image')
  dom.window.document.documentElement.className = 'electron-light'
  await settle()
  expect(dom.window.getComputedStyle(triggerDark!).display).toBe('none')
  expect(dom.window.getComputedStyle(triggerLight!).display).toBe('block')
  expect(decodeURIComponent(triggerLight?.src ?? '')).toContain('for light backgrounds')
  expect(decodeURIComponent(triggerLight?.src ?? '')).toContain('stroke="#030303"')
  dom.window.document.documentElement.className = 'electron-dark'
  await settle()
  managerTrigger?.click()
  await settle()
  const managerCard = dom.window.document.querySelector<HTMLElement>('[data-cordisx-manager-pane]')
  const managerNavigation = dom.window.document.querySelector<HTMLElement>('[data-cordisx-manager-sidebar-root]')
  expect(managerCard?.hidden).toBe(false)
  expect(managerCard?.querySelector('.cxr-pane-shell')).not.toBeNull()
  expect(managerNavigation?.querySelector('.cxr-nav')).not.toBeNull()
  expect(dom.window.document.querySelector('[data-cordisx-manager-modal]')).toBeNull()
  expect(dom.window.document.querySelector('[data-app-shell-thread-edge-divider]')?.getAttribute('aria-hidden'))
    .toBe('true')
  expect(dom.window.document.querySelector('.sidebar-header')?.getAttribute('aria-hidden')).toBe('true')
  expect(dom.window.document.querySelector('[data-app-action-sidebar-scroll]')?.getAttribute('aria-hidden'))
    .toBe('true')
  expect(managerNavigation?.querySelector('.cxr-nav')?.getAttribute('aria-label')).toBe('CordisX 管理器页面')
  expect([...managerNavigation!.querySelectorAll<HTMLElement>('.cxr-nav [data-tab]')].map(item => item.dataset.tab))
    .toEqual(['plugins', 'model-services', 'marketplace', 'extension-points', 'routes', 'notifications', 'about'])
  managerNavigation?.querySelector<HTMLButtonElement>('[data-tab="notifications"]')?.click()
  await settle()
  expect(managerCard?.querySelector('[data-notification-rules-page="true"]')?.textContent).toContain('没有屏蔽规则')
  expect(dom.window.document.querySelector('dialog.cxn-rules')).toBeNull()
  managerNavigation?.querySelector<HTMLButtonElement>('[data-tab="plugins"]')?.click()
  await settle()
  expect(managerCard?.querySelector('[data-unified-plugins-page="true"]')).not.toBeNull()
  const pluginRow = managerCard?.querySelector<HTMLButtonElement>('[data-plugin-id="slot-showcase"]')
  const artwork = await readFile(new URL('../../examples/plugins/slot-showcase/icon.png', import.meta.url))
  expect(pluginRow?.querySelector('[data-icon-kind="artwork"] img')?.getAttribute('src'))
    .toBe(`data:image/png;base64,${artwork.toString('base64')}`)
  expect(pluginRow?.textContent).toContain('点位展示')
  pluginRow?.click()
  await settle()
  expect(managerCard?.querySelector('[data-plugin-detail-tab="readme"]')).not.toBeNull()
  expect(managerCard?.querySelector('[data-plugin-detail-tab="config"]')).not.toBeNull()
  expect(managerCard?.querySelector('[role="tabpanel"][aria-label="README"] .cxm-readme')).not.toBeNull()
  await runtime?.dispose()
  expect(dom.window.document.documentElement.dataset.cordisxReady).toBeUndefined()
  expect(dom.window.document.querySelector('[data-cordisx-manager-trigger]')).toBeNull()
  expect(dom.window.document.querySelector('.cxr-brand-mark')).toBeNull()
  expect(dom.window.document.getElementById('cordisx-react-manager-style')).toBeNull()
  expect(native.parentElement).toBe(nativeParent)
  dom.window.close()
}
