import { expect } from 'vitest'
import { settle } from './bundle.fixtures.js'
import type { verifyRoutes } from './bundle.routes.js'

export async function verifyManagerShell(context: Awaited<ReturnType<typeof verifyRoutes>>) {
  const { config, plugin, bundle, dom, native, nativeParent, runtime, snapshot, sessionId, help } = context
  const managerTrigger = dom.window.document.querySelector<HTMLButtonElement>('[data-cordisx-manager-trigger]')
  expect(managerTrigger?.getAttribute('aria-label')).toBe('管理 CordisX 插件')
  expect(managerTrigger?.classList.contains('cordisx-icon-only-control')).toBe(false)
  expect(dom.window.getComputedStyle(managerTrigger!).display).toBe('inline-flex')
  expect(dom.window.getComputedStyle(managerTrigger!).alignItems).toBe('center')
  expect(dom.window.getComputedStyle(managerTrigger!).justifyContent).toBe('center')
  expect(managerTrigger?.querySelector('svg')).toBeNull()
  const triggerMark = managerTrigger?.querySelector<HTMLElement>('.cxr-trigger-mark')
  const triggerDark = triggerMark?.querySelector<HTMLImageElement>('.cxr-brand-mark-dark')
  const triggerLight = triggerMark?.querySelector<HTMLImageElement>('.cxr-brand-mark-light')
  expect(dom.window.getComputedStyle(triggerMark!).width).toBe('20px')
  expect(dom.window.getComputedStyle(triggerMark!).height).toBe('20px')
  expect(decodeURIComponent(triggerDark?.src ?? '')).toContain('for dark backgrounds')
  expect(decodeURIComponent(triggerDark?.src ?? '')).toContain('stroke="#fcfcfc"')
  expect(dom.window.document.getElementById('cordisx-react-manager-style')?.textContent).not.toContain('mask-image')
  dom.window.document.documentElement.className = 'electron-light'
  await settle()
  expect(dom.window.getComputedStyle(triggerDark!).display).toBe('none')
  expect(dom.window.getComputedStyle(triggerLight!).display).toBe('block')
  expect(decodeURIComponent(triggerLight?.src ?? '')).toContain('for light backgrounds')
  expect(decodeURIComponent(triggerLight?.src ?? '')).toContain('stroke="#030303"')
  dom.window.document.documentElement.className = 'electron-dark'
  await settle()
  managerTrigger?.click()
  await settle()
  const managerModal = dom.window.document.querySelector<HTMLElement>('[data-cordisx-manager-modal]')
  expect(managerModal?.hidden).toBe(false)
  expect(managerModal?.querySelector('.cxr-dialog')).not.toBeNull()
  expect(managerModal?.querySelector('.cxr-nav')?.getAttribute('aria-label')).toBe('CordisX 管理器页面')
  expect([...managerModal!.querySelectorAll<HTMLElement>('.cxr-nav [data-tab]')].map(item => item.dataset.tab))
    .toEqual(['plugins', 'plugin-bundles', 'extension-points', 'routes', 'marketplace', 'about'])
  const pluginRow = managerModal?.querySelector<HTMLButtonElement>('[data-plugin-id="slot-showcase"]')
  expect(pluginRow?.querySelector('[data-icon-kind="derived"]')).not.toBeNull()
  expect(pluginRow?.textContent).toContain('点位展示')
  pluginRow?.click()
  await settle()
  expect(managerModal?.querySelector('[data-plugin-detail-tab="readme"]')).not.toBeNull()
  expect(managerModal?.querySelector('[data-plugin-detail-tab="config"]')).not.toBeNull()
  expect(managerModal?.querySelector('[role="tabpanel"][aria-label="README"] .cxm-readme')).not.toBeNull()
  await runtime?.dispose()
  expect(dom.window.document.documentElement.dataset.cordisxReady).toBeUndefined()
  expect(dom.window.document.querySelector('[data-cordisx-manager-trigger]')).toBeNull()
  expect(dom.window.document.querySelector('.cxr-brand-mark')).toBeNull()
  expect(dom.window.document.getElementById('cordisx-react-manager-style')).toBeNull()
  expect(native.parentElement).toBe(nativeParent)
  dom.window.close()
}
