import type { ProductCopyCatalog } from './types.js'

export const CHANNEL_COPY = {
  'channel.title': { en: 'Channels', 'zh-CN': '渠道' },
  'channel.description': {
    en: 'Manage launcher-owned connections, routes, and task bindings.',
    'zh-CN': '管理由启动器持有的连接、路由与任务绑定。',
  },
  'channel.status.available': { en: 'Available', 'zh-CN': '可用' },
  'channel.accounts': { en: 'Accounts', 'zh-CN': '账号' },
  'channel.accounts.description': {
    en: 'Connection state and credential readiness.',
    'zh-CN': '查看连接状态与凭据就绪情况。',
  },
  'channel.accounts.empty': { en: 'No channel accounts yet.', 'zh-CN': '暂无渠道账号。' },
  'channel.accounts.empty-description': {
    en: 'Create a channel to connect CordisX to a local simulator or Feishu.',
    'zh-CN': '创建一个频道，将 CordisX 连接到本地模拟器或飞书。',
  },
  'channel.accounts.supported': { en: 'Supported channels', 'zh-CN': '当前支持的频道' },
  'channel.routes': { en: 'Routes', 'zh-CN': '路由' },
  'channel.routes.description': {
    en: 'Map channel messages to CordisX task defaults.',
    'zh-CN': '将渠道消息映射到 CordisX 任务默认项。',
  },
  'channel.routes.empty': { en: 'No channel routes yet.', 'zh-CN': '暂无渠道路由。' },
  'channel.bindings': { en: 'Task bindings', 'zh-CN': '任务绑定' },
  'channel.bindings.description': {
    en: 'Persistent channel-thread to provider-session identities.',
    'zh-CN': '持久化渠道话题与 Provider 会话的组合身份。',
  },
  'channel.bindings.empty': { en: 'No task bindings yet.', 'zh-CN': '暂无任务绑定。' },
  'channel.diagnostics': { en: 'Diagnostics', 'zh-CN': '诊断' },
  'channel.diagnostics.description': {
    en: 'Implementation and external dependency status.',
    'zh-CN': '查看实现状态与外部依赖。',
  },
  'channel.diagnostics.empty': { en: 'No diagnostics.', 'zh-CN': '暂无诊断。' },
  'channel.search.empty': { en: 'No matching items.', 'zh-CN': '没有匹配项。' },
  'channel.search.label': { en: 'Search configured channels', 'zh-CN': '搜索已配置频道' },
  'channel.search.placeholder': { en: 'Search configured channels', 'zh-CN': '搜索已配置频道' },
  'channel.search.clear': { en: 'Clear channel search', 'zh-CN': '清除频道搜索' },
  'channel.open': { en: 'Open channel details', 'zh-CN': '打开频道详情' },
  'channel.back': { en: 'Back to channels', 'zh-CN': '返回频道列表' },
  'channel.create': { en: 'New channel', 'zh-CN': '新建频道' },
  'channel.create.action': { en: 'Create channel', 'zh-CN': '创建频道' },
  'channel.create.icon-label': { en: 'Create channel configuration', 'zh-CN': '创建频道配置' },
  'channel.create.description': {
    en: 'Add a local simulator to this CordisX test configuration.',
    'zh-CN': '向当前 CordisX 测试配置添加本地模拟频道。',
  },
  'channel.create.local-only': {
    en:
      'The Host writes this simulator to the active test configuration and restarts only its local service. It has no credential and makes no external change.',
    'zh-CN': '宿主会把这个模拟频道写入当前测试配置，并只重启本地服务；不含凭据，也不会产生外部变更。',
  },
  'channel.create.name': { en: 'Channel name', 'zh-CN': '频道名称' },
  'channel.create.name-placeholder': { en: 'Enter channel name', 'zh-CN': '请输入频道名称' },
  'channel.create.platform': { en: 'Platform', 'zh-CN': '平台' },
  'channel.create.type': { en: 'Channel type', 'zh-CN': '频道类型' },
  'channel.create.type-placeholder': { en: 'Select channel type', 'zh-CN': '请选择频道类型' },
  'channel.create.introduction': { en: 'Introduction', 'zh-CN': '介绍' },
  'channel.create.introduction-placeholder': { en: 'Enter channel description', 'zh-CN': '请输入频道介绍' },
  'channel.create.no-configuration': {
    en: 'This channel type does not require additional configuration.',
    'zh-CN': '此频道类型无需额外配置。',
  },
  'channel.create.unavailable': {
    en: 'This runtime does not provide a writable Channel configuration service.',
    'zh-CN': '当前运行环境未提供可写的频道配置服务。',
  },
  'channel.create.failed': {
    en: 'The channel could not be saved. Check the local configuration service and try again.',
    'zh-CN': '频道保存失败，请检查本地配置服务后重试。',
  },
  'channel.create.save': { en: 'Confirm', 'zh-CN': '确认' },
  'channel.create.simulator': { en: 'Local simulator', 'zh-CN': '本地模拟器' },
  'channel.create.feishu': { en: 'Feishu', 'zh-CN': '飞书' },
  'channel.create.app-id': { en: 'App ID', 'zh-CN': '应用 ID' },
  'channel.create.tenant': { en: 'Tenant', 'zh-CN': '租户' },
  'channel.create.provider': { en: 'Provider', 'zh-CN': 'Provider' },
  'channel.create.model': { en: 'Model', 'zh-CN': '模型' },
  'channel.create.profile': { en: 'Profile', 'zh-CN': '配置档' },
  'channel.create.workspace': { en: 'Workspace', 'zh-CN': '工作区' },
  'channel.create.notifications': { en: 'Completion notifications', 'zh-CN': '完成通知' },
  'channel.configuration': { en: 'Configuration', 'zh-CN': '配置' },
  'channel.configuration.description': {
    en: 'Host-rendered, read-only connection information.',
    'zh-CN': '由宿主渲染的只读连接信息。',
  },
  'channel.configuration.unavailable': { en: 'No configurable items yet.', 'zh-CN': '暂无可配置项。' },
  'channel.logs': { en: 'Logs', 'zh-CN': '日志' },
  'channel.logs.unavailable': { en: 'No logs yet.', 'zh-CN': '暂无日志。' },
  'channel.logs.native-semantics': {
    en:
      'When available, logs preserve native console argument arrays and structured event records. This page does not synthesize log entries.',
    'zh-CN': '日志可用后将保留原生 console 参数数组和结构化事件记录；当前页面不会伪造日志。',
  },
  'channel.logs.search': { en: 'Search activity', 'zh-CN': '搜索活动记录' },
  'channel.logs.all': { en: 'All results', 'zh-CN': '全部结果' },
  'channel.logs.success': { en: 'Successful', 'zh-CN': '成功' },
  'channel.logs.failure': { en: 'Needs attention', 'zh-CN': '需要处理' },
  'channel.logs.export': { en: 'Export JSON', 'zh-CN': '导出 JSON' },
  'channel.logs.page': { en: 'Page', 'zh-CN': '第' },
  'channel.sessions': { en: 'Connections & sessions', 'zh-CN': '连接与会话管理' },
  'channel.sessions.unavailable': { en: 'No connected sessions yet.', 'zh-CN': '暂无连接或会话。' },
  'channel.field.platform': { en: 'Platform', 'zh-CN': '平台' },
  'channel.field.transport': { en: 'Transport', 'zh-CN': '传输方式' },
  'channel.field.enabled': { en: 'Enabled', 'zh-CN': '已启用' },
  'channel.field.status': { en: 'Connection status', 'zh-CN': '连接状态' },
  'channel.field.credentials': { en: 'Credentials', 'zh-CN': '凭据' },
  'channel.status.inbound': { en: 'Inbound pending', 'zh-CN': '待处理入站' },
  'channel.status.outbound': { en: 'Outbound pending', 'zh-CN': '待处理出站' },
  'channel.status.generation': { en: 'Service generation', 'zh-CN': '服务代次' },
  'channel.reconnect': { en: 'Reconnect', 'zh-CN': '重新连接' },
  'channel.enable': { en: 'Enable', 'zh-CN': '启用' },
  'channel.disable': { en: 'Disable', 'zh-CN': '停用' },
  'channel.reconnecting': { en: 'Reconnecting…', 'zh-CN': '正在重新连接…' },
  'channel.reconnected': { en: 'Reconnected', 'zh-CN': '已重新连接' },
  'channel.runtime.unavailable': { en: 'Runtime status is currently unavailable.', 'zh-CN': '运行状态当前不可用。' },
  'channel.binding.archive': { en: 'Archive binding', 'zh-CN': '归档绑定' },
  'channel.binding.restore': { en: 'Restore binding', 'zh-CN': '恢复绑定' },
  'channel.binding.unbind': { en: 'Unbind', 'zh-CN': '解除绑定' },
  'channel.binding-operations.unavailable': {
    en: 'Binding operations are currently unavailable.',
    'zh-CN': '绑定操作当前不可用。',
  },
  'channel.credentials.help': {
    en: 'Only readiness is projected; credential references and values are never rendered.',
    'zh-CN': '仅展示就绪状态；不会渲染凭据引用或值。',
  },
  'channel.real-readiness': { en: 'Real connection readiness', 'zh-CN': '真实连接就绪状态' },
  'channel.real-readiness.description': {
    en: 'Known test-target information is not evidence of a connected channel.',
    'zh-CN': '已知测试目标不代表频道已连接。',
  },
  'channel.real-readiness.app': {
    en: 'Feishu test application: enabled candidate cli_aaba90fcc4389cb3; not connected.',
    'zh-CN': '飞书测试应用：已启用候选 cli_aaba90fcc4389cb3；尚未连接。',
  },
  'channel.real-readiness.events': { en: 'Events and callbacks: not configured.', 'zh-CN': '事件与回调：未配置。' },
  'channel.real-readiness.credentials': { en: 'Credential reference: not configured.', 'zh-CN': '凭据引用：未配置。' },
  'channel.real-readiness.adapter': {
    en: 'Official adapter and launcher transport: unavailable.',
    'zh-CN': '官方 adapter 与启动器 transport：不可用。',
  },
  'channel.real-readiness.events-label': { en: 'Events & callbacks', 'zh-CN': '事件与回调' },
  'channel.real-readiness.adapter-label': { en: 'Adapter & transport', 'zh-CN': 'Adapter 与传输' },
} satisfies ProductCopyCatalog<'channel'>
