import type { ProductCopyCatalog } from './types.js'

export const CONSOLE_COPY = {
  'console.requests': { en: 'Requests', 'zh-CN': '调用' },
  'console.successes': { en: 'Succeeded', 'zh-CN': '成功' },
  'console.failures': { en: 'Failed', 'zh-CN': '失败' },
  'console.denied': { en: 'Denied', 'zh-CN': '拒绝' },
  'console.performance': { en: 'Performance & usage · Average duration', 'zh-CN': '性能与消费 · 平均耗时' },
  'console.no-host-api-metrics': { en: 'No Host API metrics.', 'zh-CN': '当前没有 Host API 调用计量。' },
  'console.search-placeholder': {
    en: 'Search messages, sources, or correlation ID',
    'zh-CN': '搜索消息、来源或 correlation id',
  },
  'console.all': { en: 'All', 'zh-CN': '全部' },
  'console.level': { en: 'Log level', 'zh-CN': '日志级别' },
  'console.kind': { en: 'API / type', 'zh-CN': 'API / 类型' },
  'console.source': { en: 'Log source', 'zh-CN': '日志来源' },
  'console.toolbar': { en: 'Console display controls', 'zh-CN': 'Console 显示控制' },
  'console.pause': { en: 'Pause capture', 'zh-CN': '暂停采集' },
  'console.resume': { en: 'Resume capture', 'zh-CN': '继续采集' },
  'console.follow': { en: 'Follow latest', 'zh-CN': '跟随最新' },
  'console.stop-following': { en: 'Stop following', 'zh-CN': '停止跟随' },
  'console.clear': { en: 'Clear logs', 'zh-CN': '清空日志' },
  'console.irreversible': { en: 'Cannot be undone', 'zh-CN': '不可撤销' },
  'console.copy': { en: 'Copy selected', 'zh-CN': '复制所选' },
  'console.export': { en: 'Export plugin logs', 'zh-CN': '导出插件日志' },
  'console.ownership-warning': {
    en: 'Detected {count} runtime errors with conflicting sources. Reload the plugin, then try again.',
    'zh-CN': '检测到 {count} 条来源冲突的运行时错误。请重载插件后复现。',
  },
  'console.dismiss-ownership-warning': { en: 'Dismiss attribution warning', 'zh-CN': '关闭归属异常提示' },
  'console.empty': { en: 'Waiting for plugin logs or CordisX API calls…', 'zh-CN': '等待插件日志或 CordisX API 调用…' },
  'console.no-matches': { en: 'No logs match the current filters', 'zh-CN': '没有匹配当前筛选的日志' },
  'console.back-to-latest': { en: 'Back to latest', 'zh-CN': '回到最新' },
  'console.entry-details': { en: 'Entry details', 'zh-CN': '日志详情' },
  'console.close-details': { en: 'Close log details', 'zh-CN': '关闭日志详情' },
  'console.field.timestamp': { en: 'Timestamp', 'zh-CN': '时间戳' },
  'console.field.plugin': { en: 'Plugin', 'zh-CN': '插件' },
  'console.field.generation': { en: 'Generation', 'zh-CN': 'Generation' },
  'console.field.source': { en: 'Capability / source', 'zh-CN': '能力 / 来源' },
  'console.field.kind': { en: 'Type', 'zh-CN': '类型' },
  'console.field.coverage': { en: 'Coverage', 'zh-CN': '采集' },
  'console.field.correlation': { en: 'Correlation', 'zh-CN': 'Correlation' },
  'console.field.phase': { en: 'Phase', 'zh-CN': '阶段' },
  'console.field.status': { en: 'Status', 'zh-CN': '状态' },
  'console.field.duration': { en: 'Duration', 'zh-CN': '耗时' },
  'console.field.session': { en: 'Session', 'zh-CN': '会话' },
  'console.field.trigger': { en: 'Trigger', 'zh-CN': '触发' },
  'console.field.owner': { en: 'Effective owner', 'zh-CN': '有效 owner' },
  'console.field.request-metrics': { en: 'Request metrics', 'zh-CN': '请求计量' },
  'console.field.result-metrics': { en: 'Result metrics', 'zh-CN': '结果计量' },
} satisfies ProductCopyCatalog<'console'>
