import type { ProductCopyCatalog } from './types.js'

export const FORM_COPY = {
  'form.saving': { en: 'Saving…', 'zh-CN': '正在保存…' },
  'form.dirty-prefix': { en: 'Unsaved changes', 'zh-CN': '有未保存更改' },
  'form.apply-live': { en: 'Applies immediately after saving', 'zh-CN': '保存后立即生效' },
  'form.apply-plugin-restart': { en: 'Takes effect after restarting the plugin', 'zh-CN': '保存后重启插件生效' },
  'form.apply-service-restart': { en: 'Takes effect after restarting the service', 'zh-CN': '保存后重启相关服务生效' },
  'form.apply-app-restart': { en: 'Takes effect after restarting the app', 'zh-CN': '保存后重启 App 生效' },
  'form.required': { en: 'Required', 'zh-CN': '此项为必填项' },
  'form.choice-invalid': { en: 'Choose a value from the list', 'zh-CN': '请选择列表中的有效值' },
  'form.number-invalid': { en: 'Enter a valid number', 'zh-CN': '请输入有效数字' },
  'form.natural-invalid': { en: 'Enter a non-negative integer', 'zh-CN': '请输入非负整数' },
  'form.string-length-invalid': { en: 'Enter text within the allowed length', 'zh-CN': '请输入符合长度要求的文本' },
  'form.array-invalid': { en: 'Check the number and values of items', 'zh-CN': '请检查条目数量和值' },
  'form.json-invalid': { en: 'Enter valid JSON', 'zh-CN': '请输入有效 JSON' },
  'form.sensitive-unavailable': {
    en: 'Managed by Host credentials; unavailable here.',
    'zh-CN': '敏感字段由 Host 凭据边界管理；此处不可编辑。',
  },
  'form.unsupported': { en: 'This setting cannot be edited safely.', 'zh-CN': '此设置的结构当前无法安全编辑。' },
  'form.select-placeholder': { en: 'Choose', 'zh-CN': '选择' },
  'form.text-placeholder': { en: 'Enter a value', 'zh-CN': '请输入' },
  'form.switch-on': { en: 'On', 'zh-CN': '已开启' },
  'form.switch-off': { en: 'Off', 'zh-CN': '已关闭' },
  'form.section-general': { en: 'General', 'zh-CN': '常规' },
  'form.empty-no-schema': {
    en: 'This plugin does not provide editable settings.',
    'zh-CN': '此插件未提供可编辑设置。',
  },
  'form.empty-no-fields': { en: 'This plugin has no editable settings.', 'zh-CN': '此插件没有可编辑设置。' },
  'form.restore-default': { en: 'Restore default', 'zh-CN': '恢复默认值' },
  'form.field-actions': { en: 'Field actions', 'zh-CN': '字段操作' },
  'form.use-default': { en: 'Use default value', 'zh-CN': '使用默认值' },
  'form.use-default-unavailable': { en: 'No default value is available', 'zh-CN': '此字段没有可用默认值' },
  'form.rollback-field': { en: 'Revert field change', 'zh-CN': '回滚此字段修改' },
  'form.copy-path': { en: 'Copy configuration path', 'zh-CN': '复制配置路径' },
  'form.path-copied': { en: 'Path copied', 'zh-CN': '已复制路径' },
  'form.path-copy-unavailable': { en: 'Clipboard unavailable', 'zh-CN': '剪贴板不可用' },
  'form.undo-changes': { en: 'Undo changes', 'zh-CN': '撤销更改' },
  'form.save-configuration': { en: 'Save configuration', 'zh-CN': '保存配置' },
  'form.configuration-saved': { en: 'Configuration saved', 'zh-CN': '配置已保存' },
  'form.configuration-save-failed': {
    en: 'Could not save configuration. Try again after checking the current settings.',
    'zh-CN': '配置未保存。请检查当前设置后重试。',
  },
  'form.readonly-note': {
    en: 'These settings are read-only. Connect CordisX to a writable configuration service to change them.',
    'zh-CN': '这些设置当前为只读。将 CordisX 连接到可写配置服务后即可修改。',
  },
  'form.conflict-retained': {
    en:
      'Configuration changed in another window or process. Your draft is retained; refresh and review before saving again.',
    'zh-CN': '配置已在其他窗口或进程中更新。你的草稿仍保留；刷新后请重新核对再保存。',
  },
  'form.add-item': { en: 'Add item', 'zh-CN': '添加条目' },
  'form.edit-item': { en: 'Edit item', 'zh-CN': '编辑条目' },
  'form.duplicate-item': { en: 'Duplicate item', 'zh-CN': '复制条目' },
  'form.delete-item': { en: 'Delete item', 'zh-CN': '删除条目' },
  'form.move-item-up': { en: 'Move item up', 'zh-CN': '上移条目' },
  'form.move-item-down': { en: 'Move item down', 'zh-CN': '下移条目' },
  'form.reorder-handle': { en: 'Reorder with the move controls', 'zh-CN': '使用上下移动操作调整顺序' },
  'form.array-item': { en: 'Array item', 'zh-CN': '数组条目' },
  'form.breadcrumbs': { en: 'Breadcrumbs', 'zh-CN': '面包屑' },
  'form.back': { en: 'Back', 'zh-CN': '返回' },
  'form.cancel': { en: 'Cancel', 'zh-CN': '取消' },
  'form.create-array-item': { en: 'Create array item', 'zh-CN': '创建数组项' },
  'form.edit-array-item-position': { en: 'Edit item {position}', 'zh-CN': '编辑第 {position} 项' },
  'form.create-item': { en: 'Create', 'zh-CN': '创建' },
  'form.save-item': { en: 'Save', 'zh-CN': '保存' },
  'form.item-draft-hint': { en: 'Confirm to add this item to the configuration draft', 'zh-CN': '确认后写入配置草稿' },
  'form.fix-invalid-fields': { en: 'Fix the highlighted fields before continuing', 'zh-CN': '请先修正标出的字段' },
  'form.close': { en: 'Close', 'zh-CN': '关闭' },
} satisfies ProductCopyCatalog<'form'>
