import type { ProductCopyCatalog } from './types.js'

export const MARKETPLACE_SOURCE_COPY = {
  'marketplace.description': { en: 'Manage plugin marketplace sources.', 'zh-CN': '管理插件商店来源。' },
  'marketplace.source-label': { en: 'Marketplace JSON URL', 'zh-CN': '插件商店 JSON 地址' },
  'marketplace.add': { en: 'Add marketplace', 'zh-CN': '添加商店' },
  'marketplace.empty': { en: 'No marketplaces yet.', 'zh-CN': '暂无插件商店。' },
  'marketplace.loaded': { en: 'Loaded', 'zh-CN': '已加载' },
  'marketplace.loading': { en: 'Loading…', 'zh-CN': '加载中…' },
  'marketplace.failed': { en: 'Failed to load', 'zh-CN': '加载失败' },
  'marketplace.error-details': { en: 'View error details', 'zh-CN': '查看错误详情' },
  'marketplace.move-up': { en: 'Move up', 'zh-CN': '上移' },
  'marketplace.move-down': { en: 'Move down', 'zh-CN': '下移' },
  'marketplace.remove': { en: 'Remove', 'zh-CN': '移除' },
  'marketplace.restore-official': { en: 'Restore official marketplace', 'zh-CN': '恢复官方商店' },
  'marketplace.reload': { en: 'Reload', 'zh-CN': '重新加载' },
  'marketplace.invalid-url': { en: 'Enter an HTTPS URL', 'zh-CN': '请输入 HTTPS 地址' },
  'marketplace.duplicate-source': { en: 'This marketplace is already configured', 'zh-CN': '这个商店地址已经配置' },
} satisfies ProductCopyCatalog<'marketplace'>

export const MARKETPLACE_TAB_COPY = {
  'marketplace-tab.overview': { en: 'Overview', 'zh-CN': '概览' },
  'marketplace-tab.authors-source': { en: 'Authors and source', 'zh-CN': '作者与来源' },
} satisfies ProductCopyCatalog<'marketplace-tab'>

export const MARKETPLACE_CATALOG_COPY = {
  'marketplace.heading': { en: 'Discover plugins', 'zh-CN': '发现插件' },
  'marketplace.filter-all': { en: 'Show all plugins', 'zh-CN': '显示全部插件' },
  'marketplace.filter-certified': { en: 'Show certified plugins only', 'zh-CN': '仅显示已认证插件' },
  'marketplace.filter-certified-only': { en: 'Certified only', 'zh-CN': '仅看已认证' },
  'marketplace.filter-official': { en: 'Show official plugins only', 'zh-CN': '仅显示官方插件' },
  'marketplace.filter-official-only': { en: 'Official only', 'zh-CN': '仅看官方' },
  'marketplace.official': { en: 'Official', 'zh-CN': '官方' },
  'marketplace.certified': { en: 'Certified', 'zh-CN': '已认证' },
  'marketplace.open': { en: 'Open plugin details', 'zh-CN': '打开插件详情' },
  'marketplace.collection-label': { en: 'Marketplace plugins', 'zh-CN': '插件商店列表' },
  'marketplace.search-label': { en: 'Search marketplace plugins', 'zh-CN': '搜索插件商店' },
  'marketplace.search-placeholder': { en: 'Search plugins, authors, or keywords', 'zh-CN': '搜索插件、作者或关键词' },
  'marketplace.search-clear': { en: 'Clear marketplace search', 'zh-CN': '清除商店搜索' },
  'marketplace.empty-no-sources': { en: 'No sources yet', 'zh-CN': '暂无商店来源' },
  'marketplace.no-plugins': { en: 'No plugins available', 'zh-CN': '暂无可用插件' },
  'marketplace.no-matches': { en: 'No matching plugins', 'zh-CN': '没有匹配的插件' },
  'marketplace.source-menu-label': { en: 'Manage marketplace sources', 'zh-CN': '管理商店来源' },
  'marketplace.source-menu-description': { en: 'Add, import, or manage sources', 'zh-CN': '添加、导入或管理来源' },
  'marketplace.source-menu.create': { en: 'Add source', 'zh-CN': '新增来源' },
  'marketplace.source-menu.clipboard': { en: 'Import from clipboard', 'zh-CN': '从剪贴板导入' },
  'marketplace.source-menu.manage': { en: 'Manage sources', 'zh-CN': '管理来源' },
  'marketplace.source.clipboard-prompt': {
    en: 'Paste an HTTPS URL or source file',
    'zh-CN': '粘贴 HTTPS 地址或来源文件',
  },
  'marketplace.source.clipboard-unavailable': { en: 'Clipboard unavailable', 'zh-CN': '剪贴板不可用' },
  'marketplace.source.imported': { en: 'Source imported', 'zh-CN': '已导入来源' },
  'marketplace.source.index-heading': { en: 'Marketplace sources', 'zh-CN': '商店来源' },
  'marketplace.source.add': { en: 'Add source', 'zh-CN': '新增来源' },
  'marketplace.source.disabled': { en: 'Disabled', 'zh-CN': '已停用' },
  'marketplace.source.failed': { en: 'Failed to update', 'zh-CN': '更新失败' },
  'marketplace.source.updating': { en: 'Updating', 'zh-CN': '正在更新' },
  'marketplace.source.cached': { en: 'Using cached data', 'zh-CN': '使用缓存' },
  'marketplace.source.no-description': { en: 'No description', 'zh-CN': '暂无说明' },
  'marketplace.source.open': { en: 'Open source details', 'zh-CN': '打开来源详情' },
  'marketplace.source.enable': { en: 'Enable source', 'zh-CN': '启用来源' },
  'marketplace.source.disable': { en: 'Disable source', 'zh-CN': '停用来源' },
  'marketplace.source.edit': { en: 'Edit display details', 'zh-CN': '编辑显示信息' },
  'marketplace.source.move-up': { en: 'Move up', 'zh-CN': '上移' },
  'marketplace.source.move-down': { en: 'Move down', 'zh-CN': '下移' },
  'marketplace.source.remove': { en: 'Remove source', 'zh-CN': '移除来源' },
  'marketplace.source.official-remove-unavailable': {
    en: 'The official source cannot be removed',
    'zh-CN': '官方来源不能删除',
  },
  'marketplace.source.disabled-notice': { en: 'Source disabled', 'zh-CN': '已停用来源' },
  'marketplace.source.enabled-notice': { en: 'Source enabled', 'zh-CN': '已启用来源' },
  'marketplace.source.moved-notice': { en: 'Source order updated', 'zh-CN': '已调整来源顺序' },
  'marketplace.source.removed-notice': { en: 'Source removed', 'zh-CN': '已移除来源' },
  'marketplace.source.collection-label': { en: 'Marketplace sources', 'zh-CN': '插件商店来源' },
  'marketplace.source.search-label': { en: 'Search sources', 'zh-CN': '搜索商店来源' },
  'marketplace.source.search-placeholder': { en: 'Search sources', 'zh-CN': '搜索来源' },
  'marketplace.source.search-clear': { en: 'Clear source search', 'zh-CN': '清除来源搜索' },
  'marketplace.source.empty': { en: 'No sources yet', 'zh-CN': '暂无商店来源' },
  'marketplace.source.no-matches': { en: 'No matching sources', 'zh-CN': '没有匹配的来源' },
  'marketplace.source.more-actions': { en: 'More source actions', 'zh-CN': '更多来源操作' },
  'marketplace.source.create-heading': { en: 'Add source', 'zh-CN': '添加来源' },
  'marketplace.source.edit-heading': { en: 'Source details', 'zh-CN': '来源详情' },
  'marketplace.source.url-section': { en: 'Source URL', 'zh-CN': '来源地址' },
  'marketplace.source.url-help': { en: 'Enter an HTTPS URL', 'zh-CN': '请输入 HTTPS 地址' },
  'marketplace.source.readonly-url-help': { en: 'This URL cannot be changed', 'zh-CN': '此地址不可修改' },
  'marketplace.source.url-label': { en: 'Marketplace URL', 'zh-CN': '商店地址' },
  'marketplace.source.local-section': { en: 'Display details', 'zh-CN': '显示信息' },
  'marketplace.source.local-help': { en: 'Shown only in this Manager', 'zh-CN': '仅在此管理器中显示' },
  'marketplace.source.name-label': { en: 'Name', 'zh-CN': '名称' },
  'marketplace.source.name-help': { en: 'Leave blank to use the source name', 'zh-CN': '留空时使用来源名称' },
  'marketplace.source.description-label': { en: 'Description', 'zh-CN': '说明' },
  'marketplace.source.description-help': { en: 'Describe this source', 'zh-CN': '说明此来源的内容' },
  'marketplace.source.note-label': { en: 'Note', 'zh-CN': '备注' },
  'marketplace.source.note-help': { en: 'For your reference', 'zh-CN': '仅供参考' },
  'marketplace.source.create': { en: 'Add source', 'zh-CN': '添加来源' },
  'marketplace.source.save': { en: 'Save details', 'zh-CN': '保存信息' },
  'marketplace.source.url-required': { en: 'Enter a marketplace URL', 'zh-CN': '请输入商店地址' },
  'marketplace.source.url-invalid': { en: 'Enter an HTTPS URL', 'zh-CN': '请输入有效的 HTTPS 地址' },
  'marketplace.source.duplicate': { en: 'This source is already configured', 'zh-CN': '这个来源已经配置' },
  'marketplace.source.added': { en: 'Source added', 'zh-CN': '已添加来源' },
  'marketplace.source.saved': { en: 'Details saved', 'zh-CN': '已保存信息' },
  'marketplace.source.operation-failed': { en: 'Could not update source', 'zh-CN': '无法更新来源' },
} satisfies ProductCopyCatalog<'marketplace'>
