import type { ProductCopyCatalog } from './types.js'

export const MODEL_CATALOG_COPY = {
  'catalog.configureScript': { en: 'Configure model script', 'zh-CN': '配置模型脚本' },
  'catalog.replaceScript': { en: 'Replace script configuration', 'zh-CN': '替换脚本配置' },
  'catalog.scriptNotice': {
    en:
      'Saving trusts this command to run with your user permissions, including file and network access. It is not sandboxed. Inherited or referenced environment variables may include credentials. Managed provider keys are not injected.',
    'zh-CN':
      '保存即信任此命令以本机用户权限访问文件和网络，不提供沙箱隔离。继承或引用的环境变量可能包含凭据，不会自动注入托管 Provider 密钥。',
  },
  'catalog.scriptReplaceNotice': {
    en: 'Saving replaces the entire script configuration. Existing command and environment values are not displayed.',
    'zh-CN': '保存将完整替换脚本配置，不回显已有命令和环境变量值。',
  },
  'catalog.commandKind': { en: 'Execution mode', 'zh-CN': '执行方式' },
  'catalog.exec': { en: 'Executable and arguments', 'zh-CN': '程序与参数' },
  'catalog.shell': { en: 'Shell command', 'zh-CN': 'Shell 命令' },
  'catalog.executable': { en: 'Executable or script path', 'zh-CN': '程序或脚本路径' },
  'catalog.arguments': { en: 'Arguments', 'zh-CN': '参数' },
  'catalog.addArgument': { en: 'Add argument', 'zh-CN': '添加参数' },
  'catalog.cwd': { en: 'Working directory', 'zh-CN': '工作目录' },
  'catalog.inheritEnv': { en: 'Inherit Host environment', 'zh-CN': '继承 Host 环境变量' },
  'catalog.envName': { en: 'Variable name', 'zh-CN': '变量名' },
  'catalog.envRef': { en: 'Host variable reference', 'zh-CN': 'Host 环境变量引用' },
  'catalog.envValue': { en: 'Literal value', 'zh-CN': '字面值' },
  'catalog.envKind': { en: 'Environment value source', 'zh-CN': '环境变量值来源' },
  'catalog.addEnv': { en: 'Add environment variable', 'zh-CN': '添加环境变量' },
  'catalog.removeField': { en: 'Remove field', 'zh-CN': '删除字段' },
  'catalog.scriptMode': { en: 'Model result', 'zh-CN': '模型结果' },
  'catalog.replace': { en: 'Replace model list', 'zh-CN': '替换模型列表' },
  'catalog.scriptSupplement': { en: 'Supplement model list', 'zh-CN': '补充模型列表' },
  'catalog.scriptInvalid': {
    en: 'Check the command, absolute working directory and unique environment variable names.',
    'zh-CN': '请检查命令、绝对工作目录和唯一的环境变量名称。',
  },
  'catalog.timeout': { en: 'Timeout (seconds)', 'zh-CN': '超时（秒）' },
  'catalog.sessionOnly': { en: 'Current session only', 'zh-CN': '仅当前会话' },
  'catalog.native': { en: 'Native', 'zh-CN': '原生' },
  'catalog.auto': { en: 'Automatic', 'zh-CN': '自动' },
  'catalog.manual': { en: 'Manual', 'zh-CN': '手动' },
  'catalog.script': { en: 'Script', 'zh-CN': '脚本' },
  'catalog.fresh': { en: 'Up to date', 'zh-CN': '最新' },
  'catalog.stale': { en: 'Stale', 'zh-CN': '待更新' },
  'catalog.unknown': { en: 'Not refreshed', 'zh-CN': '尚未刷新' },
  'catalog.error': { en: 'Refresh failed', 'zh-CN': '刷新失败' },
  'catalog.refreshing': { en: 'Refreshing', 'zh-CN': '刷新中' },
  'catalog.queued': { en: 'Queued', 'zh-CN': '已排队' },
  'catalog.lastSuccess': { en: 'Last refreshed', 'zh-CN': '最后刷新' },
  'catalog.lastAttempt': { en: 'Last attempt', 'zh-CN': '最后尝试' },
  'catalog.retryAt': { en: 'Retry after', 'zh-CN': '下次重试' },
  'catalog.never': { en: 'Never', 'zh-CN': '尚无' },
  'catalog.refresh': { en: 'Refresh models', 'zh-CN': '刷新模型' },
  'catalog.pause': { en: 'Pause automatic refresh', 'zh-CN': '暂停自动刷新' },
  'catalog.resume': { en: 'Resume automatic refresh', 'zh-CN': '恢复自动刷新' },
  'catalog.paused': { en: 'Automatic refresh paused', 'zh-CN': '自动刷新已暂停' },
  'catalog.selectable': { en: 'Selectable', 'zh-CN': '可选' },
  'catalog.sourceCount': { en: 'Models', 'zh-CN': '模型' },
  'catalog.block': { en: 'Block model', 'zh-CN': '屏蔽模型' },
  'catalog.unblock': { en: 'Unblock model', 'zh-CN': '解除屏蔽' },
  'catalog.pin': { en: 'Pin model', 'zh-CN': '置顶模型' },
  'catalog.unpin': { en: 'Unpin model', 'zh-CN': '取消置顶' },
  'catalog.blocked': { en: 'Blocked', 'zh-CN': '已屏蔽' },
  'catalog.removed': { en: 'Removed', 'zh-CN': '已移除' },
  'catalog.all': { en: 'All models', 'zh-CN': '全部模型' },
  'catalog.filter': { en: 'Model visibility', 'zh-CN': '模型显示范围' },
  'catalog.more': { en: 'More catalog actions', 'zh-CN': '更多目录操作' },
  'catalog.resetOrder': { en: 'Reset model order', 'zh-CN': '重置模型排序' },
  'catalog.restoreBlocked': { en: 'Unblock all models', 'zh-CN': '解除全部屏蔽' },
  'catalog.resetOrderConfirm': {
    en: 'Remove all pins for this connection, including removed models?',
    'zh-CN': '清除此连接的全部置顶，包括已移除模型的置顶？',
  },
  'catalog.restoreBlockedConfirm': {
    en: 'Clear all blocks for this connection? Removed models stay unavailable.',
    'zh-CN': '解除此连接的全部屏蔽？已移除的模型仍不可用。',
  },
  'catalog.diagnostics': { en: 'Diagnostics', 'zh-CN': '诊断' },
  'catalog.scope': { en: 'Connection confirmed', 'zh-CN': '连接已确认' },
  'catalog.unconfirmed': { en: 'Connection unconfirmed', 'zh-CN': '连接未确认' },
  'catalog.applied': { en: 'Applied', 'zh-CN': '已应用' },
  'catalog.pending-restart': { en: 'Restart required', 'zh-CN': '需要重启' },
  'catalog.conflict': {
    en: 'Catalog changed. Review the latest models before applying your draft.',
    'zh-CN': '目录已变化。请核对最新模型后重新应用草稿。',
  },
  'catalog.scopeChanged': {
    en: 'Connection changed. This draft cannot be applied to the new connection.',
    'zh-CN': '连接已变化，此草稿不能应用到新连接。',
  },
  'catalog.targetConflict': { en: 'Target has local changes', 'zh-CN': '目标存在本地修改' },
  'catalog.unavailable': { en: 'Currently unavailable', 'zh-CN': '当前不可用' },
  'catalog.failed': { en: 'Changes were not saved. Try again.', 'zh-CN': '更改未保存，请重试。' },
  'catalog.convert': { en: 'Use these models manually', 'zh-CN': '将当前结果转为手动目录' },
  'catalog.convertConfirm': {
    en: 'Take over this model list manually? Automatic discovery stops; blocks and pins stay unchanged.',
    'zh-CN': '手动接管当前模型列表？自动发现将停止，屏蔽和置顶保持不变。',
  },
  'catalog.editManual': { en: 'Edit manual models', 'zh-CN': '编辑手动模型' },
  'catalog.editSupplement': { en: 'Edit supplemental models', 'zh-CN': '编辑补充模型' },
  'catalog.notListed': { en: 'Not officially listed; added by you', 'zh-CN': '官方未列出，由用户补充' },
  'catalog.supplement': { en: 'Supplement', 'zh-CN': '用户补充' },
  'catalog.id': { en: 'Exact model ID', 'zh-CN': '精确模型 ID' },
  'catalog.label': { en: 'Display name (optional)', 'zh-CN': '显示名称（可选）' },
  'catalog.addModel': { en: 'Add model', 'zh-CN': '添加模型' },
  'catalog.removeModel': { en: 'Remove model declaration', 'zh-CN': '删除模型声明' },
  'catalog.save': { en: 'Save', 'zh-CN': '保存' },
  'catalog.cancel': { en: 'Cancel', 'zh-CN': '取消' },
  'catalog.confirm': { en: 'Confirm', 'zh-CN': '确认' },
  'catalog.close': { en: 'Close', 'zh-CN': '关闭' },
  'catalog.emptyConfirm': { en: 'Save an empty list', 'zh-CN': '确认保存空列表' },
  'catalog.invalid': {
    en: 'Use unique, non-empty model IDs without control characters.',
    'zh-CN': '模型 ID 必须唯一、非空且不含控制字符。',
  },
  'catalog.latest': { en: 'Latest model IDs', 'zh-CN': '最新模型 ID' },
  'catalog.reviewed': { en: 'Use latest revision', 'zh-CN': '采用最新版本后重试' },
  'catalog.added': { en: 'Added', 'zh-CN': '已新增' },
  'catalog.deleted': { en: 'Removed', 'zh-CN': '已移除' },
  'catalog.source': { en: 'Model source', 'zh-CN': '模型来源' },
  'catalog.autoOnly': { en: 'Automatic only', 'zh-CN': '仅自动结果' },
  'catalog.autoAugment': { en: 'Automatic with supplements', 'zh-CN': '自动结果与用户补充' },
  'catalog.manualReplace': { en: 'Manual replacement', 'zh-CN': '手动接管' },
  'catalog.useAuto': { en: 'Use automatic discovery', 'zh-CN': '切换为自动发现' },
  'catalog.useAutoConfirm': {
    en: 'Replace manual authority with automatic discovery? Blocks and pins stay unchanged.',
    'zh-CN': '以自动发现替代手动目录？屏蔽和置顶保持不变。',
  },
  'catalog.enableSupplement': { en: 'Include supplemental models', 'zh-CN': '包含用户补充模型' },
  'catalog.disableSupplement': { en: 'Use source models only', 'zh-CN': '仅使用来源模型' },
  'catalog.modeConfirm': {
    en: 'Change whether supplemental models are included? Saved declarations are retained.',
    'zh-CN': '更改是否包含用户补充模型？已有补充声明将保留。',
  },
  'catalog.runScript': { en: 'Run script', 'zh-CN': '运行脚本' },
  'catalog.cancelScript': { en: 'Cancel script', 'zh-CN': '取消运行' },
  'catalog.scriptUnavailable': { en: 'Script execution unavailable', 'zh-CN': '脚本执行暂不可用' },
  'catalog.replaceCredential': { en: 'Replace credential', 'zh-CN': '更换凭据' },
  'catalog.replaceConfirm': {
    en: 'Continue to secure credential entry? Existing connection history is isolated after replacement.',
    'zh-CN': '继续安全输入凭据？更换后旧连接历史将隔离。',
  },
  'catalog.clearSupplementFirst': {
    en: 'Remove supplemental models before replacing this credential.',
    'zh-CN': '更换凭据前请先移除补充模型。',
  },
  'catalog.addConnection': { en: 'Add model connection', 'zh-CN': '添加模型连接' },
  'catalog.editConnection': { en: 'Edit connection', 'zh-CN': '编辑连接' },
  'catalog.title': { en: 'Name', 'zh-CN': '名称' },
  'catalog.endpoint': { en: 'Endpoint', 'zh-CN': '服务地址' },
  'catalog.protocol': { en: 'Protocol', 'zh-CN': '协议' },
  'catalog.discoveryGrant': { en: 'Allow automatic model discovery', 'zh-CN': '允许自动发现模型' },
  'catalog.connectionInvalid': {
    en: 'Enter a name and an HTTPS endpoint without credentials or query parameters.',
    'zh-CN': '请输入名称和不含凭据或查询参数的 HTTPS 服务地址。',
  },
  'catalog.showMore': { en: 'Show more models', 'zh-CN': '显示更多模型' },
  'catalog.noModels': { en: 'No models', 'zh-CN': '暂无模型' },
} as const satisfies ProductCopyCatalog<'catalog'>
