import type { ProductCopyCatalog } from './types.js'

export const PLUGIN_COLLECTION_COPY = {
  'plugins.install': { en: 'Import local plugin', 'zh-CN': '导入本地插件' },
  'plugins.install-checking': { en: 'Checking local package', 'zh-CN': '检查本地包中' },
  'plugins.enable': { en: 'Enable plugin', 'zh-CN': '启用插件' },
  'plugins.disable': { en: 'Disable plugin', 'zh-CN': '禁用插件' },
  'plugins.favorite': { en: 'Favorite plugin', 'zh-CN': '收藏插件' },
  'plugins.unfavorite': { en: 'Remove from favorites', 'zh-CN': '取消收藏' },
  'plugins.reload': { en: 'Reload plugin', 'zh-CN': '重载插件' },
  'plugins.open': { en: 'Open plugin details', 'zh-CN': '打开插件详情' },
  'plugins.heading': { en: 'Plugin details', 'zh-CN': '插件详情' },
  'plugins.local-development': { en: 'Local development', 'zh-CN': '本地开发' },
  'plugins.development': { en: 'Development build', 'zh-CN': '开发态' },
  'plugins.project-link': { en: 'Project link', 'zh-CN': '项目链接' },
  'plugins.details-actions': { en: 'Plugin information and actions', 'zh-CN': '插件信息与操作' },
  'plugins.details-tabs': { en: 'Plugin details', 'zh-CN': '插件详情' },
  'plugins.missing': { en: 'This plugin is no longer available.', 'zh-CN': '插件已不存在' },
  'plugins.no-readme': { en: 'This plugin does not provide a README.', 'zh-CN': '此插件没有提供 README。' },
  'plugins.operation-result': { en: 'Operation result', 'zh-CN': '操作结果' },
  'plugins.source-path': { en: 'Source path', 'zh-CN': '源码路径' },
  'plugins.build-status': { en: 'Build status', 'zh-CN': '构建状态' },
  'plugins.last-success': { en: 'Last successful build', 'zh-CN': '最近成功' },
  'plugins.metric.requests': { en: 'Requests', 'zh-CN': '请求' },
  'plugins.metric.successes': { en: 'Succeeded', 'zh-CN': '成功' },
  'plugins.metric.failures': { en: 'Failed', 'zh-CN': '失败' },
  'plugins.metric.denials': { en: 'Denied', 'zh-CN': '拒绝' },
  'plugins.metric.status': { en: 'Status', 'zh-CN': '状态' },
  'plugins.metric.permissions': { en: 'Permissions', 'zh-CN': '权限' },
  'plugins.metric.extension-points': { en: 'Extension points', 'zh-CN': '扩展点' },
  'plugins.metric.routes': { en: 'Routes', 'zh-CN': '路由' },
  'plugins.metric.injected-capabilities': { en: 'Injected capabilities', 'zh-CN': '注入能力' },
  'plugins.metric.dependencies': { en: 'Dependencies', 'zh-CN': '依赖' },
  'plugins.injected-capabilities': { en: 'Injected capabilities', 'zh-CN': '注入能力' },
  'plugins.none': { en: 'None', 'zh-CN': '无' },
  'plugins.no-permissions': {
    en: 'This plugin does not declare platform permissions.',
    'zh-CN': '该插件未声明平台权限',
  },
  'plugins.search-extension-points': { en: 'Search plugin extension points', 'zh-CN': '搜索插件扩展点' },
  'plugins.search-extension-points-placeholder': {
    en: 'Search extension points, descriptions, or IDs…',
    'zh-CN': '搜索扩展点、介绍或 id…',
  },
  'plugins.no-extension-points': { en: 'This plugin does not use extension points.', 'zh-CN': '该插件未使用扩展点' },
  'plugins.no-matching-extension-points': { en: 'No matching extension points', 'zh-CN': '没有匹配的扩展点' },
  'plugins.search-routes': { en: 'Search plugin routes', 'zh-CN': '搜索插件路由' },
  'plugins.search-routes-placeholder': { en: 'Search titles, paths, or IDs…', 'zh-CN': '搜索标题、路径或 id…' },
  'plugins.no-routes': { en: 'This plugin does not register routes.', 'zh-CN': '该插件未注册路由' },
  'plugins.no-matching-routes': { en: 'No matching routes', 'zh-CN': '没有匹配的路由' },
} satisfies ProductCopyCatalog<'plugins'>

export const PLUGIN_STATUS_COPY = {
  'plugin.status.active': { en: 'Active', 'zh-CN': '运行中' },
  'plugin.status.blocked': { en: 'Blocked', 'zh-CN': '已屏蔽' },
  'plugin.status.permission-blocked': { en: 'Permission blocked', 'zh-CN': '权限阻止' },
  'plugin.status.failed': { en: 'Failed to start', 'zh-CN': '启动失败' },
  'plugin.status.installing': { en: 'Installing', 'zh-CN': '安装中' },
  'plugin.status.updating': { en: 'Updating', 'zh-CN': '更新中' },
  'plugin.status.enabling': { en: 'Enabling', 'zh-CN': '启用中' },
  'plugin.status.disabling': { en: 'Disabling', 'zh-CN': '禁用中' },
  'plugin.status.reloading': { en: 'Reloading', 'zh-CN': '重载中' },
  'plugin.status.uninstalling': { en: 'Uninstalling', 'zh-CN': '卸载中' },
  'plugin.status.rolling-back': { en: 'Restoring', 'zh-CN': '正在恢复' },
  'plugin.status.rollback-failed': { en: 'Restore failed', 'zh-CN': '恢复失败' },
  'plugin.status.configured-disabled': { en: 'Disabled by configuration', 'zh-CN': '配置禁用' },
} satisfies ProductCopyCatalog<'plugin'>

export const PLUGIN_SHARING_DEMO_COPY = {
  'plugins.share': { en: 'Share public source', 'zh-CN': '分享公开来源' },
  'plugins.share-unavailable': { en: 'Share public source (unavailable)', 'zh-CN': '分享公开来源（不可用）' },
  'plugins.open-source': { en: 'Open public source', 'zh-CN': '打开公开来源' },
  'plugins.open-source-unavailable': { en: 'Open public source (unavailable)', 'zh-CN': '打开公开来源（不可用）' },
  'plugins.diagnostics': { en: 'View diagnostics', 'zh-CN': '查看运行诊断' },
  'plugins.uninstall': { en: 'Uninstall', 'zh-CN': '卸载' },
  'plugins.uninstall-unavailable': { en: 'Uninstall (unavailable)', 'zh-CN': '卸载（不可用）' },
  'plugins.local-description': { en: 'Local CordisX plugin', 'zh-CN': '本地 CordisX 插件' },
  'plugins.collection-label': { en: 'Current bundle plugins', 'zh-CN': '当前 bundle 插件' },
  'plugins.search-label': { en: 'Search plugins', 'zh-CN': '搜索 CordisX 插件' },
  'plugins.search-placeholder': { en: 'Search plugins or extension points', 'zh-CN': '搜索插件或扩展点' },
  'plugins.search-clear': { en: 'Clear plugin search', 'zh-CN': '清除插件搜索' },
  'plugins.empty': { en: 'No plugins available', 'zh-CN': '暂无可用插件' },
  'plugins.no-matches': { en: 'No matching plugins', 'zh-CN': '没有匹配的插件' },
  'plugins.more-actions': { en: 'More plugin actions', 'zh-CN': '更多插件操作' },
  'plugins.operation-busy': { en: 'Another plugin action is in progress', 'zh-CN': '当前有插件操作正在执行' },
  'plugins.enable-unavailable': { en: 'This plugin cannot be enabled now', 'zh-CN': '插件当前不能启用' },
  'plugins.disable-unavailable': { en: 'This plugin cannot be disabled now', 'zh-CN': '插件当前不能禁用' },
  'plugins.reload-unavailable': { en: 'This plugin cannot be reloaded now', 'zh-CN': '插件当前不能重载' },
  'plugins.demo.slot-showcase-description': {
    en: 'Explore plugins, navigation, pages, and status.',
    'zh-CN': '查看插件、导航、页面与状态。',
  },
  'plugins.demo.hello-toolbar-description': {
    en: 'Add a quick greeting to the workspace toolbar.',
    'zh-CN': '在工作区工具栏添加快捷问候。',
  },
  'plugins.demo.form-schema-gallery-description': {
    en: 'Explore editable workspace settings.',
    'zh-CN': '查看可编辑的工作区设置。',
  },
} satisfies ProductCopyCatalog<'plugins'>

export const PLUGIN_TAB_COPY = {
  'plugin-tab.readme': { en: 'README', 'zh-CN': 'README' },
  'plugin-tab.configuration': { en: 'Configuration', 'zh-CN': '配置管理' },
  'plugin-tab.permissions': { en: 'Permissions', 'zh-CN': '权限' },
  'plugin-tab.runtime': { en: 'Runtime status', 'zh-CN': '运行状态' },
  'plugin-tab.logs': { en: 'Logs & diagnostics', 'zh-CN': '日志与诊断' },
  'plugin-tab.extension-points': { en: 'Extension points', 'zh-CN': '扩展点位' },
  'plugin-tab.routes': { en: 'Routes', 'zh-CN': '路由' },
} satisfies ProductCopyCatalog<'plugin-tab'>
