import React from 'react'
import type {
  CordisXMessageDefinition,
  CordisXMessageSchema,
  CordisXPageMount,
  CordisXReactPageComponent,
} from './contracts.js'

export {
  act,
  Activity,
  cache,
  cacheSignal,
  captureOwnerStack,
  Children,
  cloneElement,
  Component,
  createContext,
  createElement,
  createRef,
  forwardRef,
  Fragment,
  isValidElement,
  lazy,
  memo,
  Profiler,
  PureComponent,
  startTransition,
  StrictMode,
  Suspense,
  use,
  useActionState,
  useCallback,
  useContext,
  useDebugValue,
  useDeferredValue,
  useEffect,
  useEffectEvent,
  useId,
  useImperativeHandle,
  useInsertionEffect,
  useLayoutEffect,
  useMemo,
  useOptimistic,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  useTransition,
  version,
} from 'react'
export type {
  ActionDispatch,
  AllHTMLAttributes,
  AnchorHTMLAttributes,
  AriaAttributes,
  Attributes,
  ButtonHTMLAttributes,
  ChangeEvent,
  ChangeEventHandler,
  ClassAttributes,
  ComponentProps,
  ComponentPropsWithoutRef,
  ComponentPropsWithRef,
  ComponentRef,
  ComponentState,
  ComponentType,
  Context,
  CSSProperties,
  Dispatch,
  DOMAttributes,
  EffectCallback,
  ElementRef,
  ElementType,
  FC,
  FocusEvent,
  FocusEventHandler,
  FormEvent,
  FormEventHandler,
  ForwardedRef,
  ForwardRefExoticComponent,
  FunctionComponent,
  HTMLAttributes,
  InputHTMLAttributes,
  JSX,
  JSXElementConstructor,
  Key,
  KeyboardEvent,
  KeyboardEventHandler,
  MouseEvent,
  MouseEventHandler,
  MutableRefObject,
  NamedExoticComponent,
  PropsWithChildren,
  ReactElement,
  ReactEventHandler,
  ReactNode,
  Reducer,
  Ref,
  RefAttributes,
  RefCallback,
  RefObject,
  SelectHTMLAttributes,
  SetStateAction,
  SyntheticEvent,
  TextareaHTMLAttributes,
  TransitionFunction,
  UIEvent,
  UIEventHandler,
} from 'react'
export default React

/**
 * Public authoring type and Node-side placeholder. CordisX plugin builds
 * replace this module with the Host-owned implementation before execution.
 */
export function defineReactPage<
  Messages extends CordisXMessageDefinition<Messages> = CordisXMessageSchema,
>(component: CordisXReactPageComponent<Messages>): CordisXPageMount<Messages> {
  void component
  return () => {
    throw new Error('defineReactPage is available only inside the CordisX renderer Host')
  }
}
